// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
)

const createShoppingItem = `-- name: CreateShoppingItem :exec
INSERT INTO shopping_items (name, item_type)
VALUES ($1, $2)
`

type CreateShoppingItemParams struct {
	Name     string
	ItemType ShoppingItemType
}

func (q *Queries) CreateShoppingItem(ctx context.Context, arg CreateShoppingItemParams) error {
	_, err := q.db.Exec(ctx, createShoppingItem, arg.Name, arg.ItemType)
	return err
}

const listShoppingItems = `-- name: ListShoppingItems :many
SELECT id, name, item_type
FROM shopping_items
`

func (q *Queries) ListShoppingItems(ctx context.Context) ([]ShoppingItem, error) {
	rows, err := q.db.Query(ctx, listShoppingItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingItem
	for rows.Next() {
		var i ShoppingItem
		if err := rows.Scan(&i.ID, &i.Name, &i.ItemType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
