package shoppinglist

var ShoppingList = []ShoppingItem{
	{"Shallot 🧅", Veg},
	{"Red Peppers 🌶️", Veg},
	{"Cucumber 🥒", Veg},
	{"Butternut Squash 🎃", Veg},
	{"Sage 🍃", Veg},
	{"Basil 🌿", Veg},
	{"Apple Juice 🧃", Drinks},
	{"Mozzarella 🫕", Dairy},
	{"Risotto Rice 🍚", Pantry},
	{"Duck Eggs 🍳", Dairy},
	{"Crisps 🍟", Snacks},
	{"Glass Spray 🪞", Cleaning},
	{"Pasta 🍝", Pantry},
	{"Pizza Bases 🍕", Bakery},
	{"Squid 🦑", Seafood},
	{"Marmite 🍞", Condiments},
	{"Chocolate 🍫", Snacks},
	{"Quorn 🍗", MeatFree},
	{"Cereal 🥣", Pantry},
	{"Christmas Cards 🎄", Household},
	{"Grapes 🍇", Fruit},
	{"Cheese Tasters 🧀", Dairy},
	{"Ribena 🍇", Drinks},
	{"Blister Plasters 🩹", Health},
	{"Apples 🍎", Fruit},
	{"Lettuce 🥬", Veg},
	{"Fishcakes 🐧", Seafood},
	{"Pie 🥧", Bakery},
	{"Baby Snacks 👶", Baby},
	{"Tortilla Chips 🌮", Snacks},
	{"Marrowfat Peas 🫛", Pantry},
	{"Boullion Powder 🥘", Pantry},
	{"Green Beans 🫛", Veg},
	{"Cabbage 🥬", Veg},
	{"Coconut Milk 🥥", Pantry},
	{"Wine 🍷", Drinks},
	{"Spinach 🍃", Veg},
	{"Chickpeas 🫘", Pantry},
	{"Apple Cider Vinegar 🍏", Condiments},
	{"Marshmallows 🍭", Snacks},
	{"Chocolate Chips 🍪", Snacks},
	{"Chocolate Spread 🍫🥖", Snacks},
	{"Chia Seeds 🌾", Pantry},
	{"Cherry Jam 🍒", Condiments},
	{"Ice Bags 🧊", Household},
	{"Chocolate Milk 🍫 🥛", Drinks},
	{"Black Beans 🫘", Pantry},
	{"Salad 🥗", Veg},
	{"Pancakes 🥞", Bakery},
	{"Stuffing 🥘", Pantry},
	{"Whipped Cream 🥛", Dairy},
	{"Plum Jam 🍈", Condiments},
	{"Blueberries 🫐", Fruit},
	{"Flour 🌾", Pantry},
	{"Baby Wipes 🧻", Baby},
	{"Cling Film 🫙", Household},
	{"Vitamins 💊", Health},
	{"Cauliflower 🥦", Veg},
	{"Lasagne 🍝", Pantry},
	{"Wrapping Paper 🎁", Household},
	{"Newspaper 📰", Household},
	{"Broccoli 🥦", Veg},
	{"Olive Oil 🫒", Condiments},
	{"Beans 🫘", Pantry},
	{"Soup 🥣", Pantry},
	{"Snacks 🍿", Snacks},
	{"Veggie Bacon 🥓", MeatFree},
	{"Pitta Pockets 🥙", Bakery},
	{"Breadcrumbs 🍞", Pantry},
	{"Pecan Nuts 🌰", Pantry},
	{"Walnuts 🌰", Pantry},
	{"Arrowroot Powder 🧂", Pantry},
	{"Cocktails 🍸", Drinks},
	{"Dry Shampoo 🧴", Toiletries},
	{"Pudding 🍮", Dairy},
	{"Fennel 🥬", Veg},
	{"Peppercorn Sauce 🧂", Condiments},
	{"Buckwheat Flour 🌾", Pantry},
	{"Calamari 🦑", Seafood},
	{"Cornflour 🌽", Pantry},
	{"Parsley 🌿", Veg},
	{"Fabric Softener 🧺", Cleaning},
	{"Mashed Potatoes 🍚", Pantry},
	{"Veggie Burgers 🍔", MeatFree},
	{"Peas 🫛", Veg},
	{"Thyme 🌿", Veg},
	{"Oregano 🌿", Veg},
	{"Celery Salt 🧂", Spices},
	{"Mustard 🌭", Condiments},
	{"Smoked Paprika 🌶️", Spices},
	{"White Pepper 🫑", Spices},
	{"Stuffed Chicken 🍗", Meat},
	{"Dark Chocolate Chips 🍫", Snacks},
	{"Milk Chocolate Chips 🍫", Snacks},
	{"Courgettes 🥒", Veg},
	{"Baking Powder 🧂", Pantry},
	{"Bicarbonate of Soda 🧂", Pantry},
	{"Stock Cubes 🍲", Pantry},
	{"Prawns 🦐", Seafood},
	{"Mustard Seeds 🌱", Spices},
	{"Turmeric Powder🌼", Spices},
	{"Ginger Powder 🫚", Spices},
	{"Chilli Flakes 🌶️", Spices},
	{"Dark Chocolate 🍫", Snacks},
	{"Butter 🧈", Dairy},
	{"Tropical Juice 🥭 🍍", Drinks},
	{"Tampons 🦈", Toiletries},
	{"Nigella Seeds 🪴", Spices},
	{"Cocoa Powder🍫", Pantry},
	{"Quorn Slices 🥪", MeatFree},
	{"Baked Potatoes 🥔", Veg},
	{"Ground Almonds 🌰", Pantry},
	{"Xanthum Gum 🍭", Pantry},
	{"Icing Sugar 🧂", Pantry},
	{"Strawberries 🍓", Fruit},
	{"Unsalted Butter 🧈", Dairy},
	{"Spaghetti 🍝", Pantry},
	{"Pasta Sauce 🥫", Pantry},
	{"Sparkling Water 🧊", Drinks},
	{"Lime Cordial 🍋‍🟩", Drinks},
	{"Toothbrush 🪥", Toiletries},
	{"Oat Biscuits 🍪", Snacks},
	{"Crackers 🧇", Snacks},
	{"Balsamic Vinegar 🫗", Condiments},
	{"Cleaning Sponges 🧽", Cleaning},
	{"Lemons 🍋", Fruit},
	{"Pinto Beans 🫘", Pantry},
	{"Tortillas 🫓", Bakery},
	{"Rice Cakes 🍚", Snacks},
	{"Cherries 🍒", Fruit},
	{"Celery 🥬", Veg},
	{"Pastry 🥧", Bakery},
	{"Nuts 🥜", Pantry},
	{"Dates 🥭", Fruit},
	{"Compost 🪴", Household},
	{"Pizza 🍕", Frozen},
	{"Daim Cake 🍫", Snacks},
	{"Cleaning Cream 🧽", Cleaning},
	{"Toilet Cleaner 🚽", Cleaning},
	{"Zoflora 🌼", Cleaning},
	{"Chocolate Bar 🍫", Snacks},
	{"Jazz Apples 🍎", Fruit},
	{"Tomato Soup 🥫", Pantry},
	{"Eggs 🍳", Dairy},
	{"Ice Cream 🍨", Frozen},
	{"Peanut Butter 🥜", Pantry},
	{"Ironing Water 💧", Household},
	{"Leeks 🥬", Veg},
	{"Milk 🥛", Dairy},
	{"Oats 🌾", Pantry},
	{"Bananas 🍌", Fruit},
	{"Baking Parchment 📜", Household},
	{"Rocket 🥬", Veg},
	{"Tissues 🧻", Household},
	{"Brussel Sprouts 🥬", Veg},
	{"Noodles 🍜", Pantry},
	{"Fries 🍟", Frozen},
	{"Fish 🐟", Seafood},
	{"Bread Rolls 🥯", Bakery},
	{"Fruit Juice 🧃", Drinks},
	{"Maple Syrup 🍁", Condiments},
	{"Lemsip 💊", Health},
	{"Ketchup 🍅", Condiments},
	{"Coffee ☕️", Drinks},
	{"Washing Up Liquid 🧼", Cleaning},
	{"Sweets 🍬", Snacks},
	{"Aubergine 🍆", Veg},
	{"Toilet Roll 🧻", Household},
	{"Green Vegetables 🥬", Veg},
	{"Onion 🧅", Veg},
	{"Red Cabbage 🥬", Veg},
	{"Sweet Potato 🍠", Veg},
	{"Coriander 🌿", Veg},
	{"Limes 🍋‍🟩", Fruit},
	{"Blackberries 🍇", Fruit},
	{"Yoghurt 🥛", Dairy},
	{"Kitchen Spray 🧼", Cleaning},
	{"Bathroom Spray 🛁", Cleaning},
	{"Rice 🍚", Pantry},
	{"Spring Rolls 🥡", Frozen},
	{"Sweet Corn 🌽", Veg},
	{"Baked Beans 🫘", Pantry},
	{"Kitchen Roll 🧻", Household},
	{"Laundry Powder 🧺", Cleaning},
	{"Bin Bags 🗑️", Household},
	{"Drain Cleaner 🫧", Cleaning},
	{"Bread 🍞", Bakery},
	{"Noodle Pots 🥡", Pantry},
	{"Puy Lentils 🫘", Pantry},
	{"Tomato Passata 🥫", Pantry},
	{"Potatoes 🥔", Veg},
	{"Carrots 🥕", Veg},
	{"Mushrooms 🍄‍🟫", Veg},
	{"Tomatoes 🍅", Veg},
	{"Cheese 🧀", Dairy},
	{"Burgers 🍔", MeatFree},
	{"Yorkshire Puddings 🥘", Frozen},
	{"Juice 🧃", Drinks},
	{"Cereal Bars 🫔", Snacks},
	{"Soya Milk 🥛", Drinks},
	{"Beer 🍻", Drinks},
	{"Pizza Sauce 🥫", Pantry},
	{"Pizza Cheese 🧀", Dairy},
	{"Olives 🫒", Pantry},
	{"Biscuits 🍪", Snacks},
	{"Red Leicester Slices 🧀", Dairy},
	{"Oat Milk 🥛", Drinks},
}
