package database

// meal_plan_weeks.go
//
// Hand-written query wrappers for week-aware meal plan operations introduced
// in migration 010 (week_start DATE column).
//
// These are NOT generated by sqlc. They live here because the sqlc-generated
// files cannot be modified, and re-running sqlc would require the actual
// database to be running. All query logic matches the patterns in the
// generated code exactly.

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

// WeekStart returns the Monday of the ISO week containing t, truncated to
// midnight UTC. This is the canonical key used for week_start in meal_plan.
func WeekStart(t time.Time) time.Time {
	t = t.UTC().Truncate(24 * time.Hour)
	// Weekday(): Sunday=0, Monday=1 … Saturday=6
	// We want days-since-Monday: Monday→0, Tuesday→1 … Sunday→6
	offset := (int(t.Weekday()) + 6) % 7
	return t.AddDate(0, 0, -offset)
}

// ── Param / row types ─────────────────────────────────────────────────────────

// GetWeekPlanParams selects one week's meal_plan rows for a scope.
type GetWeekPlanParams struct {
	WeekStart   time.Time   `json:"week_start"`
	HouseholdID pgtype.Int4 `json:"household_id"`
	UserID      pgtype.Int4 `json:"user_id"`
}

// GetWeekPlanRow is the full row returned by GetWeekPlan, including all four
// repeating/temp slots and joined meal/cook names.
type GetWeekPlanRow struct {
	ID                    int32            `json:"id"`
	DayName               string           `json:"day_name"`
	WeekStart             time.Time        `json:"week_start"`
	MealID                pgtype.Int4      `json:"meal_id"`
	CookUserID            pgtype.Int4      `json:"cook_user_id"`
	RepeatingMealID       pgtype.Int4      `json:"repeating_meal_id"`
	RepeatingCookUserID   pgtype.Int4      `json:"repeating_cook_user_id"`
	TempMealID            pgtype.Int4      `json:"temp_meal_id"`
	TempCookUserID        pgtype.Int4      `json:"temp_cook_user_id"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	MealName              pgtype.Text      `json:"meal_name"`
	DefaultPortions       pgtype.Int4      `json:"default_portions"`
	MealDescription       pgtype.Text      `json:"meal_description"`
	CookName              pgtype.Text      `json:"cook_name"`
	CookUsername          pgtype.Text      `json:"cook_username"`
	RepeatingMealName     pgtype.Text      `json:"repeating_meal_name"`
	TempMealName          pgtype.Text      `json:"temp_meal_name"`
	RepeatingCookName     pgtype.Text      `json:"repeating_cook_name"`
	RepeatingCookUsername pgtype.Text      `json:"repeating_cook_username"`
	TempCookName          pgtype.Text      `json:"temp_cook_name"`
	TempCookUsername      pgtype.Text      `json:"temp_cook_username"`
}

// SetWeekPlanDayParams upserts one day within a specific week.
type SetWeekPlanDayParams struct {
	DayName             string      `json:"day_name"`
	WeekStart           time.Time   `json:"week_start"`
	MealID              pgtype.Int4 `json:"meal_id"`
	CookUserID          pgtype.Int4 `json:"cook_user_id"`
	RepeatingMealID     pgtype.Int4 `json:"repeating_meal_id"`
	RepeatingCookUserID pgtype.Int4 `json:"repeating_cook_user_id"`
	TempMealID          pgtype.Int4 `json:"temp_meal_id"`
	TempCookUserID      pgtype.Int4 `json:"temp_cook_user_id"`
	HouseholdID         pgtype.Int4 `json:"household_id"`
	UserID              pgtype.Int4 `json:"user_id"`
}

// GenerateWeekParams creates a week's plan rows by copying the most recent
// repeating assignments for each day into the target week for a given scope.
type GenerateWeekParams struct {
	TargetWeekStart time.Time   `json:"target_week_start"`
	HouseholdID     pgtype.Int4 `json:"household_id"`
	UserID          pgtype.Int4 `json:"user_id"`
}

// ── Query functions ───────────────────────────────────────────────────────────

const getWeekPlan = `
SELECT
    mp.id,
    mp.day_name,
    mp.week_start,
    mp.meal_id,
    mp.cook_user_id,
    mp.repeating_meal_id,
    mp.repeating_cook_user_id,
    mp.temp_meal_id,
    mp.temp_cook_user_id,
    mp.updated_at,
    em.name            AS meal_name,
    em.default_portions,
    em.description     AS meal_description,
    ecu.name           AS cook_name,
    ecu.username       AS cook_username,
    rm.name            AS repeating_meal_name,
    tm.name            AS temp_meal_name,
    rcu.name           AS repeating_cook_name,
    rcu.username       AS repeating_cook_username,
    tcu.name           AS temp_cook_name,
    tcu.username       AS temp_cook_username
FROM meal_plan mp
LEFT JOIN meals  em  ON em.id  = mp.meal_id
LEFT JOIN users  ecu ON ecu.id = mp.cook_user_id
LEFT JOIN meals  rm  ON rm.id  = mp.repeating_meal_id
LEFT JOIN meals  tm  ON tm.id  = mp.temp_meal_id
LEFT JOIN users  rcu ON rcu.id = mp.repeating_cook_user_id
LEFT JOIN users  tcu ON tcu.id = mp.temp_cook_user_id
WHERE mp.week_start = $1
  AND (mp.household_id = $2 OR mp.user_id = $3)
ORDER BY CASE mp.day_name
    WHEN 'Monday'    THEN 1
    WHEN 'Tuesday'   THEN 2
    WHEN 'Wednesday' THEN 3
    WHEN 'Thursday'  THEN 4
    WHEN 'Friday'    THEN 5
    WHEN 'Saturday'  THEN 6
    WHEN 'Sunday'    THEN 7
    ELSE 8 END`

// GetWeekPlan returns all meal_plan rows for the given week and scope.
func GetWeekPlan(ctx context.Context, db *pgxpool.Pool, arg GetWeekPlanParams) ([]GetWeekPlanRow, error) {
	rows, err := db.Query(ctx, getWeekPlan, arg.WeekStart, arg.HouseholdID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWeekPlanRow
	for rows.Next() {
		var i GetWeekPlanRow
		if err := rows.Scan(
			&i.ID, &i.DayName, &i.WeekStart,
			&i.MealID, &i.CookUserID,
			&i.RepeatingMealID, &i.RepeatingCookUserID,
			&i.TempMealID, &i.TempCookUserID,
			&i.UpdatedAt,
			&i.MealName, &i.DefaultPortions, &i.MealDescription,
			&i.CookName, &i.CookUsername,
			&i.RepeatingMealName, &i.TempMealName,
			&i.RepeatingCookName, &i.RepeatingCookUsername,
			&i.TempCookName, &i.TempCookUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const setWeekPlanDayHousehold = `
INSERT INTO meal_plan (
    day_name, week_start,
    meal_id, cook_user_id,
    repeating_meal_id, repeating_cook_user_id,
    temp_meal_id, temp_cook_user_id,
    household_id, user_id, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (day_name, week_start, household_id) WHERE household_id IS NOT NULL
DO UPDATE SET
    meal_id                = EXCLUDED.meal_id,
    cook_user_id           = EXCLUDED.cook_user_id,
    repeating_meal_id      = EXCLUDED.repeating_meal_id,
    repeating_cook_user_id = EXCLUDED.repeating_cook_user_id,
    temp_meal_id           = EXCLUDED.temp_meal_id,
    temp_cook_user_id      = EXCLUDED.temp_cook_user_id,
    updated_at             = now()`

const setWeekPlanDayUser = `
INSERT INTO meal_plan (
    day_name, week_start,
    meal_id, cook_user_id,
    repeating_meal_id, repeating_cook_user_id,
    temp_meal_id, temp_cook_user_id,
    household_id, user_id, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (day_name, week_start, user_id) WHERE user_id IS NOT NULL
DO UPDATE SET
    meal_id                = EXCLUDED.meal_id,
    cook_user_id           = EXCLUDED.cook_user_id,
    repeating_meal_id      = EXCLUDED.repeating_meal_id,
    repeating_cook_user_id = EXCLUDED.repeating_cook_user_id,
    temp_meal_id           = EXCLUDED.temp_meal_id,
    temp_cook_user_id      = EXCLUDED.temp_cook_user_id,
    updated_at             = now()`

// SetWeekPlanDay upserts one day within the given week for a scope.
// It uses the household-scoped conflict clause when household_id is set,
// and the user-scoped clause otherwise.
func SetWeekPlanDay(ctx context.Context, db *pgxpool.Pool, arg SetWeekPlanDayParams) error {
	q := setWeekPlanDayUser
	if arg.HouseholdID.Valid {
		q = setWeekPlanDayHousehold
	}
	_, err := db.Exec(ctx, q,
		arg.DayName, arg.WeekStart,
		arg.MealID, arg.CookUserID,
		arg.RepeatingMealID, arg.RepeatingCookUserID,
		arg.TempMealID, arg.TempCookUserID,
		arg.HouseholdID, arg.UserID,
	)
	return err
}

const generateNextWeek = `
INSERT INTO meal_plan (
    day_name, week_start,
    meal_id, cook_user_id,
    repeating_meal_id, repeating_cook_user_id,
    temp_meal_id, temp_cook_user_id,
    household_id, user_id, updated_at
)
SELECT
    day_name,
    $2 AS week_start,
    -- Effective values for the new week come from the repeating slots
    repeating_meal_id      AS meal_id,
    repeating_cook_user_id AS cook_user_id,
    -- Carry the repeating assignments forward unchanged
    repeating_meal_id,
    repeating_cook_user_id,
    -- No temp overrides for a freshly generated week
    NULL AS temp_meal_id,
    NULL AS temp_cook_user_id,
    household_id,
    user_id,
    now()
FROM (
    -- Use the most recent row per (day_name, scope) as the source of the
    -- repeating config, not a fixed week_start. This means generation works
    -- correctly even when the target week has never had rows before, and even
    -- when the repeating config was set in an older week.
    SELECT DISTINCT ON (day_name, household_id, user_id)
        day_name,
        repeating_meal_id,
        repeating_cook_user_id,
        household_id,
        user_id
    FROM meal_plan
    WHERE (household_id = $1 OR user_id = $3)
      AND (repeating_meal_id IS NOT NULL OR repeating_cook_user_id IS NOT NULL)
    ORDER BY day_name, household_id, user_id, week_start DESC
) latest
-- Skip days where this week already has a row (DO NOTHING equivalent via WHERE NOT EXISTS)
WHERE NOT EXISTS (
    SELECT 1 FROM meal_plan existing
    WHERE existing.day_name    = latest.day_name
      AND existing.week_start  = $2
      AND (
          (latest.household_id IS NOT NULL AND existing.household_id = latest.household_id) OR
          (latest.user_id      IS NOT NULL AND existing.user_id      = latest.user_id)
      )
)`

// GenerateNextWeek copies the repeating assignments into target_week for the
// given scope. It sources from the most recent row per day per scope so that
// generation works correctly even when no rows exist for the target week yet.
// Days that already have a row for target_week are left untouched.
func GenerateNextWeek(ctx context.Context, db *pgxpool.Pool, arg GenerateWeekParams) (int64, error) {
	tag, err := db.Exec(ctx, generateNextWeek,
		arg.HouseholdID, arg.TargetWeekStart,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

// DistinctScopeRow holds one (household_id, user_id) pair from meal_plan.
type DistinctScopeRow struct {
	HouseholdID pgtype.Int4
	UserID      pgtype.Int4
}

const distinctScopes = `
SELECT DISTINCT household_id, user_id
FROM meal_plan
WHERE repeating_meal_id IS NOT NULL OR repeating_cook_user_id IS NOT NULL`

// DistinctScopes returns every (household_id, user_id) scope that has at
// least one repeating assignment in meal_plan. Used by the scheduler to
// know which scopes need a next-week plan generated.
func DistinctScopes(ctx context.Context, db *pgxpool.Pool) ([]DistinctScopeRow, error) {
	rows, err := db.Query(ctx, distinctScopes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []DistinctScopeRow
	for rows.Next() {
		var r DistinctScopeRow
		if err := rows.Scan(&r.HouseholdID, &r.UserID); err != nil {
			return nil, err
		}
		out = append(out, r)
	}
	return out, rows.Err()
}
