package database

// UserHousehold is the lightweight household representation returned by the
// GetUserByUsername query via JSON_AGG. The query only selects household_id
// and name — num_people is intentionally omitted from that aggregation.
//
// This file is hand-written and NOT generated by sqlc. Do not delete it.
type UserHousehold struct {
	HouseholdID int32  `json:"household_id"`
	Name        string `json:"name"`
}
