// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cook_log.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCookReviewCandidates = `-- name: ListCookReviewCandidates :many

SELECT
    (mp.week_start + (CASE mp.day_name
        WHEN 'Monday'    THEN 0 WHEN 'Tuesday'  THEN 1 WHEN 'Wednesday' THEN 2
        WHEN 'Thursday'  THEN 3 WHEN 'Friday'   THEN 4 WHEN 'Saturday'  THEN 5
        WHEN 'Sunday'    THEN 6 ELSE 0 END))::date AS cook_date,
    mp.day_name,
    mp.meal_id,
    m.name             AS meal_name,
    m.default_portions,
    mp.household_id,
    mp.user_id
FROM meal_plan mp
JOIN meals m ON m.id = mp.meal_id
WHERE (mp.household_id = $1 OR mp.user_id = $2)
  AND mp.meal_id IS NOT NULL
  AND (mp.week_start + (CASE mp.day_name
        WHEN 'Monday'    THEN 0 WHEN 'Tuesday'  THEN 1 WHEN 'Wednesday' THEN 2
        WHEN 'Thursday'  THEN 3 WHEN 'Friday'   THEN 4 WHEN 'Saturday'  THEN 5
        WHEN 'Sunday'    THEN 6 ELSE 0 END))::date BETWEEN $3 AND $4
  AND NOT EXISTS (
      SELECT 1 FROM meal_cook_log l
      WHERE l.meal_id = mp.meal_id
        AND l.cook_date = (mp.week_start + (CASE mp.day_name
            WHEN 'Monday'    THEN 0 WHEN 'Tuesday'  THEN 1 WHEN 'Wednesday' THEN 2
            WHEN 'Thursday'  THEN 3 WHEN 'Friday'   THEN 4 WHEN 'Saturday'  THEN 5
            WHEN 'Sunday'    THEN 6 ELSE 0 END))::date
        AND (
            (l.household_id IS NOT NULL AND l.household_id = mp.household_id) OR
            (l.user_id      IS NOT NULL AND l.user_id      = mp.user_id)
        )
  )
ORDER BY cook_date
`

type ListCookReviewCandidatesParams struct {
	HouseholdID pgtype.Int4 `json:"household_id"`
	UserID      pgtype.Int4 `json:"user_id"`
	WeekStart   pgtype.Date `json:"week_start"`
	WeekStart_2 pgtype.Date `json:"week_start_2"`
}

type ListCookReviewCandidatesRow struct {
	CookDate        pgtype.Date `json:"cook_date"`
	DayName         string      `json:"day_name"`
	MealID          pgtype.Int4 `json:"meal_id"`
	MealName        string      `json:"meal_name"`
	DefaultPortions int32       `json:"default_portions"`
	HouseholdID     pgtype.Int4 `json:"household_id"`
	UserID          pgtype.Int4 `json:"user_id"`
}

// Cook-review queries: candidate past meals to confirm, and the answer log.
//
// A meal_plan row's real date is week_start (a Monday) plus the weekday offset
// of day_name. We compute that inline as cook_date.
// Planned meals for a scope whose date falls in [since, until] and that the
// user has not already answered. Pass household_id/user_id per the usual scope
// convention (exactly one is non-NULL).
func (q *Queries) ListCookReviewCandidates(ctx context.Context, arg ListCookReviewCandidatesParams) ([]ListCookReviewCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listCookReviewCandidates,
		arg.HouseholdID,
		arg.UserID,
		arg.WeekStart,
		arg.WeekStart_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCookReviewCandidatesRow
	for rows.Next() {
		var i ListCookReviewCandidatesRow
		if err := rows.Scan(
			&i.CookDate,
			&i.DayName,
			&i.MealID,
			&i.MealName,
			&i.DefaultPortions,
			&i.HouseholdID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMealCookLog = `-- name: UpsertMealCookLog :exec
INSERT INTO meal_cook_log (meal_id, cook_date, made, household_id, user_id, answered_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT DO NOTHING
`

type UpsertMealCookLogParams struct {
	MealID      int32       `json:"meal_id"`
	CookDate    pgtype.Date `json:"cook_date"`
	Made        bool        `json:"made"`
	HouseholdID pgtype.Int4 `json:"household_id"`
	UserID      pgtype.Int4 `json:"user_id"`
	AnsweredBy  pgtype.Int4 `json:"answered_by"`
}

// Record the answer to "did you make this?" Idempotent per (scope, date, meal).
func (q *Queries) UpsertMealCookLog(ctx context.Context, arg UpsertMealCookLogParams) error {
	_, err := q.db.Exec(ctx, upsertMealCookLog,
		arg.MealID,
		arg.CookDate,
		arg.Made,
		arg.HouseholdID,
		arg.UserID,
		arg.AnsweredBy,
	)
	return err
}
