// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: households.sql

package database

import (
	"context"
)

const insertHousehold = `-- name: InsertHousehold :exec
INSERT INTO households (household_id)
VALUES ($1)
`

func (q *Queries) InsertHousehold(ctx context.Context, householdID int32) error {
	_, err := q.db.Exec(ctx, insertHousehold, householdID)
	return err
}
