// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meal_option_groups.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMealOptionGroupEntry = `-- name: AddMealOptionGroupEntry :one
INSERT INTO meal_option_group_entries
    (meal_id, option_group, option_type, sort_order, shopping_item_id, sub_meal_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, meal_id, option_group, option_type, sort_order, shopping_item_id, sub_meal_id
`

type AddMealOptionGroupEntryParams struct {
	MealID         int32       `json:"meal_id"`
	OptionGroup    string      `json:"option_group"`
	OptionType     string      `json:"option_type"`
	SortOrder      int32       `json:"sort_order"`
	ShoppingItemID pgtype.Int4 `json:"shopping_item_id"`
	SubMealID      pgtype.Int4 `json:"sub_meal_id"`
}

func (q *Queries) AddMealOptionGroupEntry(ctx context.Context, arg AddMealOptionGroupEntryParams) (MealOptionGroupEntry, error) {
	row := q.db.QueryRow(ctx, addMealOptionGroupEntry,
		arg.MealID,
		arg.OptionGroup,
		arg.OptionType,
		arg.SortOrder,
		arg.ShoppingItemID,
		arg.SubMealID,
	)
	var i MealOptionGroupEntry
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.OptionGroup,
		&i.OptionType,
		&i.SortOrder,
		&i.ShoppingItemID,
		&i.SubMealID,
	)
	return i, err
}

const getMealOptionGroups = `-- name: GetMealOptionGroups :many
SELECT
    e.id,
    e.meal_id,
    e.option_group,
    e.option_type,
    e.sort_order,
    e.shopping_item_id,
    e.sub_meal_id,
    si.name  AS item_name,
    sm.name  AS sub_meal_name
FROM meal_option_group_entries e
LEFT JOIN shopping_items si ON si.id = e.shopping_item_id
LEFT JOIN meals          sm ON sm.id = e.sub_meal_id
WHERE e.meal_id = $1
ORDER BY e.option_group, e.sort_order, e.id
`

type GetMealOptionGroupsRow struct {
	ID             int32       `json:"id"`
	MealID         int32       `json:"meal_id"`
	OptionGroup    string      `json:"option_group"`
	OptionType     string      `json:"option_type"`
	SortOrder      int32       `json:"sort_order"`
	ShoppingItemID pgtype.Int4 `json:"shopping_item_id"`
	SubMealID      pgtype.Int4 `json:"sub_meal_id"`
	ItemName       pgtype.Text `json:"item_name"`
	SubMealName    pgtype.Text `json:"sub_meal_name"`
}

// Returns all option group entries for a meal, ordered by group then sort_order.
func (q *Queries) GetMealOptionGroups(ctx context.Context, mealID int32) ([]GetMealOptionGroupsRow, error) {
	rows, err := q.db.Query(ctx, getMealOptionGroups, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMealOptionGroupsRow
	for rows.Next() {
		var i GetMealOptionGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.OptionGroup,
			&i.OptionType,
			&i.SortOrder,
			&i.ShoppingItemID,
			&i.SubMealID,
			&i.ItemName,
			&i.SubMealName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMealOptionGroupEntry = `-- name: RemoveMealOptionGroupEntry :exec
DELETE FROM meal_option_group_entries
WHERE id = $1 AND meal_id = $2
`

type RemoveMealOptionGroupEntryParams struct {
	ID     int32 `json:"id"`
	MealID int32 `json:"meal_id"`
}

func (q *Queries) RemoveMealOptionGroupEntry(ctx context.Context, arg RemoveMealOptionGroupEntryParams) error {
	_, err := q.db.Exec(ctx, removeMealOptionGroupEntry, arg.ID, arg.MealID)
	return err
}

const updateMealOptionGroupEntry = `-- name: UpdateMealOptionGroupEntry :one
UPDATE meal_option_group_entries
SET option_group     = $2,
    option_type      = $3,
    sort_order       = $4,
    shopping_item_id = $5,
    sub_meal_id      = $6
WHERE id = $1
RETURNING id, meal_id, option_group, option_type, sort_order, shopping_item_id, sub_meal_id
`

type UpdateMealOptionGroupEntryParams struct {
	ID             int32       `json:"id"`
	OptionGroup    string      `json:"option_group"`
	OptionType     string      `json:"option_type"`
	SortOrder      int32       `json:"sort_order"`
	ShoppingItemID pgtype.Int4 `json:"shopping_item_id"`
	SubMealID      pgtype.Int4 `json:"sub_meal_id"`
}

func (q *Queries) UpdateMealOptionGroupEntry(ctx context.Context, arg UpdateMealOptionGroupEntryParams) (MealOptionGroupEntry, error) {
	row := q.db.QueryRow(ctx, updateMealOptionGroupEntry,
		arg.ID,
		arg.OptionGroup,
		arg.OptionType,
		arg.SortOrder,
		arg.ShoppingItemID,
		arg.SubMealID,
	)
	var i MealOptionGroupEntry
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.OptionGroup,
		&i.OptionType,
		&i.SortOrder,
		&i.ShoppingItemID,
		&i.SubMealID,
	)
	return i, err
}
