// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meal_plan_repeating.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearAllTempOverrides = `-- name: ClearAllTempOverrides :exec
UPDATE meal_plan
SET temp_meal_id      = NULL,
    temp_cook_user_id = NULL,
    meal_id           = COALESCE(repeating_meal_id, meal_id),
    cook_user_id      = COALESCE(repeating_cook_user_id, cook_user_id),
    updated_at        = now()
WHERE household_id = $1 OR user_id = $2
`

type ClearAllTempOverridesParams struct {
	HouseholdID pgtype.Int4 `json:"household_id"`
	UserID      pgtype.Int4 `json:"user_id"`
}

// Week-rollover bulk clear for a household or user scope.
func (q *Queries) ClearAllTempOverrides(ctx context.Context, arg ClearAllTempOverridesParams) error {
	_, err := q.db.Exec(ctx, clearAllTempOverrides, arg.HouseholdID, arg.UserID)
	return err
}

const clearTempOverridesForDay = `-- name: ClearTempOverridesForDay :exec
UPDATE meal_plan
SET temp_meal_id      = NULL,
    temp_cook_user_id = NULL,
    -- Promote repeating values into the effective slots
    meal_id           = repeating_meal_id,
    cook_user_id      = repeating_cook_user_id,
    updated_at        = now()
WHERE day_name = $1
  AND (household_id = $2 OR user_id = $3)
`

type ClearTempOverridesForDayParams struct {
	DayName     string      `json:"day_name"`
	HouseholdID pgtype.Int4 `json:"household_id"`
	UserID      pgtype.Int4 `json:"user_id"`
}

// Called at week rollover: wipes temp fields so the repeating values take effect.
func (q *Queries) ClearTempOverridesForDay(ctx context.Context, arg ClearTempOverridesForDayParams) error {
	_, err := q.db.Exec(ctx, clearTempOverridesForDay, arg.DayName, arg.HouseholdID, arg.UserID)
	return err
}

const getMealPlanFullV2 = `-- name: GetMealPlanFullV2 :many
SELECT
    mp.id,
    mp.day_name,

    -- Effective (resolved) values — what actually runs this week
    mp.meal_id,
    mp.cook_user_id,

    -- Repeating defaults
    mp.repeating_meal_id,
    mp.repeating_cook_user_id,

    -- One-off overrides for the coming week
    mp.temp_meal_id,
    mp.temp_cook_user_id,

    mp.updated_at,

    -- Effective meal details
    em.name            AS meal_name,
    em.default_portions,
    em.description     AS meal_description,

    -- Effective cook details
    ecu.name           AS cook_name,
    ecu.username       AS cook_username,

    -- Repeating meal name
    rm.name            AS repeating_meal_name,

    -- Temp meal name
    tm.name            AS temp_meal_name,

    -- Repeating cook name
    rcu.name           AS repeating_cook_name,
    rcu.username       AS repeating_cook_username,

    -- Temp cook name
    tcu.name           AS temp_cook_name,
    tcu.username       AS temp_cook_username

FROM meal_plan mp
LEFT JOIN meals  em  ON em.id  = mp.meal_id
LEFT JOIN users  ecu ON ecu.id = mp.cook_user_id
LEFT JOIN meals  rm  ON rm.id  = mp.repeating_meal_id
LEFT JOIN meals  tm  ON tm.id  = mp.temp_meal_id
LEFT JOIN users  rcu ON rcu.id = mp.repeating_cook_user_id
LEFT JOIN users  tcu ON tcu.id = mp.temp_cook_user_id
WHERE mp.household_id = $1 OR mp.user_id = $2
ORDER BY CASE mp.day_name
    WHEN 'Monday'    THEN 1
    WHEN 'Tuesday'   THEN 2
    WHEN 'Wednesday' THEN 3
    WHEN 'Thursday'  THEN 4
    WHEN 'Friday'    THEN 5
    WHEN 'Saturday'  THEN 6
    WHEN 'Sunday'    THEN 7
    ELSE 8 END
`

type GetMealPlanFullV2Params struct {
	HouseholdID pgtype.Int4 `json:"household_id"`
	UserID      pgtype.Int4 `json:"user_id"`
}

type GetMealPlanFullV2Row struct {
	ID                    int32            `json:"id"`
	DayName               string           `json:"day_name"`
	MealID                pgtype.Int4      `json:"meal_id"`
	CookUserID            pgtype.Int4      `json:"cook_user_id"`
	RepeatingMealID       pgtype.Int4      `json:"repeating_meal_id"`
	RepeatingCookUserID   pgtype.Int4      `json:"repeating_cook_user_id"`
	TempMealID            pgtype.Int4      `json:"temp_meal_id"`
	TempCookUserID        pgtype.Int4      `json:"temp_cook_user_id"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	MealName              pgtype.Text      `json:"meal_name"`
	DefaultPortions       pgtype.Int4      `json:"default_portions"`
	MealDescription       pgtype.Text      `json:"meal_description"`
	CookName              pgtype.Text      `json:"cook_name"`
	CookUsername          pgtype.Text      `json:"cook_username"`
	RepeatingMealName     pgtype.Text      `json:"repeating_meal_name"`
	TempMealName          pgtype.Text      `json:"temp_meal_name"`
	RepeatingCookName     pgtype.Text      `json:"repeating_cook_name"`
	RepeatingCookUsername pgtype.Text      `json:"repeating_cook_username"`
	TempCookName          pgtype.Text      `json:"temp_cook_name"`
	TempCookUsername      pgtype.Text      `json:"temp_cook_username"`
}

// Returns the week plan with all four cook/meal slots plus resolved effective values.
func (q *Queries) GetMealPlanFullV2(ctx context.Context, arg GetMealPlanFullV2Params) ([]GetMealPlanFullV2Row, error) {
	rows, err := q.db.Query(ctx, getMealPlanFullV2, arg.HouseholdID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMealPlanFullV2Row
	for rows.Next() {
		var i GetMealPlanFullV2Row
		if err := rows.Scan(
			&i.ID,
			&i.DayName,
			&i.MealID,
			&i.CookUserID,
			&i.RepeatingMealID,
			&i.RepeatingCookUserID,
			&i.TempMealID,
			&i.TempCookUserID,
			&i.UpdatedAt,
			&i.MealName,
			&i.DefaultPortions,
			&i.MealDescription,
			&i.CookName,
			&i.CookUsername,
			&i.RepeatingMealName,
			&i.TempMealName,
			&i.RepeatingCookName,
			&i.RepeatingCookUsername,
			&i.TempCookName,
			&i.TempCookUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMealPlanDayV2Household = `-- name: SetMealPlanDayV2Household :one
INSERT INTO meal_plan (
    day_name, week_start,
    meal_id,          cook_user_id,
    repeating_meal_id, repeating_cook_user_id,
    temp_meal_id,      temp_cook_user_id,
    household_id, user_id, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NULL, now())
ON CONFLICT (day_name, week_start, household_id) WHERE household_id IS NOT NULL
DO UPDATE SET
    meal_id                 = EXCLUDED.meal_id,
    cook_user_id            = EXCLUDED.cook_user_id,
    repeating_meal_id       = EXCLUDED.repeating_meal_id,
    repeating_cook_user_id  = EXCLUDED.repeating_cook_user_id,
    temp_meal_id            = EXCLUDED.temp_meal_id,
    temp_cook_user_id       = EXCLUDED.temp_cook_user_id,
    updated_at              = now()
RETURNING id, day_name, week_start, meal_name, household_id, user_id, updated_at, meal_id, cook_user_id, repeating_cook_user_id, temp_cook_user_id, repeating_meal_id, temp_meal_id
`

type SetMealPlanDayV2HouseholdParams struct {
	DayName             string      `json:"day_name"`
	WeekStart           pgtype.Date `json:"week_start"`
	MealID              pgtype.Int4 `json:"meal_id"`
	CookUserID          pgtype.Int4 `json:"cook_user_id"`
	RepeatingMealID     pgtype.Int4 `json:"repeating_meal_id"`
	RepeatingCookUserID pgtype.Int4 `json:"repeating_cook_user_id"`
	TempMealID          pgtype.Int4 `json:"temp_meal_id"`
	TempCookUserID      pgtype.Int4 `json:"temp_cook_user_id"`
	HouseholdID         pgtype.Int4 `json:"household_id"`
}

// Upserts a household-scoped day entry, including the four repeating/temp slots.
// Uses the idx_meal_plan_day_week_household partial index (migration 010).
func (q *Queries) SetMealPlanDayV2Household(ctx context.Context, arg SetMealPlanDayV2HouseholdParams) (MealPlan, error) {
	row := q.db.QueryRow(ctx, setMealPlanDayV2Household,
		arg.DayName,
		arg.WeekStart,
		arg.MealID,
		arg.CookUserID,
		arg.RepeatingMealID,
		arg.RepeatingCookUserID,
		arg.TempMealID,
		arg.TempCookUserID,
		arg.HouseholdID,
	)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.DayName,
		&i.WeekStart,
		&i.MealName,
		&i.HouseholdID,
		&i.UserID,
		&i.UpdatedAt,
		&i.MealID,
		&i.CookUserID,
		&i.RepeatingCookUserID,
		&i.TempCookUserID,
		&i.RepeatingMealID,
		&i.TempMealID,
	)
	return i, err
}

const setMealPlanDayV2User = `-- name: SetMealPlanDayV2User :one
INSERT INTO meal_plan (
    day_name, week_start,
    meal_id,          cook_user_id,
    repeating_meal_id, repeating_cook_user_id,
    temp_meal_id,      temp_cook_user_id,
    household_id, user_id, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NULL, $9, now())
ON CONFLICT (day_name, week_start, user_id) WHERE user_id IS NOT NULL
DO UPDATE SET
    meal_id                 = EXCLUDED.meal_id,
    cook_user_id            = EXCLUDED.cook_user_id,
    repeating_meal_id       = EXCLUDED.repeating_meal_id,
    repeating_cook_user_id  = EXCLUDED.repeating_cook_user_id,
    temp_meal_id            = EXCLUDED.temp_meal_id,
    temp_cook_user_id       = EXCLUDED.temp_cook_user_id,
    updated_at              = now()
RETURNING id, day_name, week_start, meal_name, household_id, user_id, updated_at, meal_id, cook_user_id, repeating_cook_user_id, temp_cook_user_id, repeating_meal_id, temp_meal_id
`

type SetMealPlanDayV2UserParams struct {
	DayName             string      `json:"day_name"`
	WeekStart           pgtype.Date `json:"week_start"`
	MealID              pgtype.Int4 `json:"meal_id"`
	CookUserID          pgtype.Int4 `json:"cook_user_id"`
	RepeatingMealID     pgtype.Int4 `json:"repeating_meal_id"`
	RepeatingCookUserID pgtype.Int4 `json:"repeating_cook_user_id"`
	TempMealID          pgtype.Int4 `json:"temp_meal_id"`
	TempCookUserID      pgtype.Int4 `json:"temp_cook_user_id"`
	UserID              pgtype.Int4 `json:"user_id"`
}

// Upserts a user-scoped day entry, including the four repeating/temp slots.
// Uses the idx_meal_plan_day_week_user partial index (migration 010).
func (q *Queries) SetMealPlanDayV2User(ctx context.Context, arg SetMealPlanDayV2UserParams) (MealPlan, error) {
	row := q.db.QueryRow(ctx, setMealPlanDayV2User,
		arg.DayName,
		arg.WeekStart,
		arg.MealID,
		arg.CookUserID,
		arg.RepeatingMealID,
		arg.RepeatingCookUserID,
		arg.TempMealID,
		arg.TempCookUserID,
		arg.UserID,
	)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.DayName,
		&i.WeekStart,
		&i.MealName,
		&i.HouseholdID,
		&i.UserID,
		&i.UpdatedAt,
		&i.MealID,
		&i.CookUserID,
		&i.RepeatingCookUserID,
		&i.TempCookUserID,
		&i.RepeatingMealID,
		&i.TempMealID,
	)
	return i, err
}

const upsertMealPlanDayHousehold = `-- name: UpsertMealPlanDayHousehold :one
INSERT INTO meal_plan (day_name, week_start, meal_name, household_id, user_id, updated_at)
VALUES ($1, DATE_TRUNC('week', CURRENT_DATE)::DATE, $2, $3, NULL, now())
ON CONFLICT (day_name, week_start, household_id) WHERE household_id IS NOT NULL
DO UPDATE SET
    meal_name  = EXCLUDED.meal_name,
    updated_at = now()
RETURNING id, day_name, week_start, meal_name, household_id, user_id, updated_at, meal_id, cook_user_id, repeating_cook_user_id, temp_cook_user_id, repeating_meal_id, temp_meal_id
`

type UpsertMealPlanDayHouseholdParams struct {
	DayName     string      `json:"day_name"`
	MealName    pgtype.Text `json:"meal_name"`
	HouseholdID pgtype.Int4 `json:"household_id"`
}

// Simple upsert for household-scoped days (meal_name + effective meal/cook only).
// Uses the idx_meal_plan_day_week_household partial index (migration 010).
func (q *Queries) UpsertMealPlanDayHousehold(ctx context.Context, arg UpsertMealPlanDayHouseholdParams) (MealPlan, error) {
	row := q.db.QueryRow(ctx, upsertMealPlanDayHousehold, arg.DayName, arg.MealName, arg.HouseholdID)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.DayName,
		&i.WeekStart,
		&i.MealName,
		&i.HouseholdID,
		&i.UserID,
		&i.UpdatedAt,
		&i.MealID,
		&i.CookUserID,
		&i.RepeatingCookUserID,
		&i.TempCookUserID,
		&i.RepeatingMealID,
		&i.TempMealID,
	)
	return i, err
}

const upsertMealPlanDayUser = `-- name: UpsertMealPlanDayUser :one
INSERT INTO meal_plan (day_name, week_start, meal_name, household_id, user_id, updated_at)
VALUES ($1, DATE_TRUNC('week', CURRENT_DATE)::DATE, $2, NULL, $3, now())
ON CONFLICT (day_name, week_start, user_id) WHERE user_id IS NOT NULL
DO UPDATE SET
    meal_name  = EXCLUDED.meal_name,
    updated_at = now()
RETURNING id, day_name, week_start, meal_name, household_id, user_id, updated_at, meal_id, cook_user_id, repeating_cook_user_id, temp_cook_user_id, repeating_meal_id, temp_meal_id
`

type UpsertMealPlanDayUserParams struct {
	DayName  string      `json:"day_name"`
	MealName pgtype.Text `json:"meal_name"`
	UserID   pgtype.Int4 `json:"user_id"`
}

// Simple upsert for user-scoped days (meal_name + effective meal/cook only).
// Uses the idx_meal_plan_day_week_user partial index (migration 010).
func (q *Queries) UpsertMealPlanDayUser(ctx context.Context, arg UpsertMealPlanDayUserParams) (MealPlan, error) {
	row := q.db.QueryRow(ctx, upsertMealPlanDayUser, arg.DayName, arg.MealName, arg.UserID)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.DayName,
		&i.WeekStart,
		&i.MealName,
		&i.HouseholdID,
		&i.UserID,
		&i.UpdatedAt,
		&i.MealID,
		&i.CookUserID,
		&i.RepeatingCookUserID,
		&i.TempCookUserID,
		&i.RepeatingMealID,
		&i.TempMealID,
	)
	return i, err
}
