// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meals.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMealIngredient = `-- name: AddMealIngredient :one
INSERT INTO meal_ingredients (meal_id, shopping_item_id, quantity, unit)
VALUES ($1, $2, $3, $4)
RETURNING meal_id, shopping_item_id, quantity, unit
`

type AddMealIngredientParams struct {
	MealID         int32          `json:"meal_id"`
	ShoppingItemID int32          `json:"shopping_item_id"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           pgtype.Text    `json:"unit"`
}

func (q *Queries) AddMealIngredient(ctx context.Context, arg AddMealIngredientParams) (MealIngredient, error) {
	row := q.db.QueryRow(ctx, addMealIngredient,
		arg.MealID,
		arg.ShoppingItemID,
		arg.Quantity,
		arg.Unit,
	)
	var i MealIngredient
	err := row.Scan(
		&i.MealID,
		&i.ShoppingItemID,
		&i.Quantity,
		&i.Unit,
	)
	return i, err
}

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (name, description, default_portions)
VALUES ($1, $2, $3)
RETURNING id, name, description, default_portions
`

type CreateMealParams struct {
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	DefaultPortions int32       `json:"default_portions"`
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, createMeal, arg.Name, arg.Description, arg.DefaultPortions)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DefaultPortions,
	)
	return i, err
}

const deleteMeal = `-- name: DeleteMeal :exec
DELETE FROM meals
WHERE id = $1
`

func (q *Queries) DeleteMeal(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMeal, id)
	return err
}

const getMeal = `-- name: GetMeal :one
SELECT id, name, description, default_portions FROM meals
WHERE id = $1
`

func (q *Queries) GetMeal(ctx context.Context, id int32) (Meal, error) {
	row := q.db.QueryRow(ctx, getMeal, id)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DefaultPortions,
	)
	return i, err
}

const getMealWithIngredients = `-- name: GetMealWithIngredients :many
SELECT
    m.id              AS meal_id,
    m.name            AS meal_name,
    m.description     AS meal_description,
    m.default_portions,
    mi.shopping_item_id,
    mi.quantity,
    mi.unit,
    si.name           AS ingredient_name,
    si.item_type      AS ingredient_type,
    si.portions_per_unit
FROM meals m
JOIN meal_ingredients mi ON mi.meal_id = m.id
JOIN shopping_items si   ON si.id = mi.shopping_item_id
WHERE m.id = $1
ORDER BY si.name
`

type GetMealWithIngredientsRow struct {
	MealID          int32            `json:"meal_id"`
	MealName        string           `json:"meal_name"`
	MealDescription pgtype.Text      `json:"meal_description"`
	DefaultPortions int32            `json:"default_portions"`
	ShoppingItemID  int32            `json:"shopping_item_id"`
	Quantity        pgtype.Numeric   `json:"quantity"`
	Unit            pgtype.Text      `json:"unit"`
	IngredientName  string           `json:"ingredient_name"`
	IngredientType  ShoppingItemType `json:"ingredient_type"`
	PortionsPerUnit int32            `json:"portions_per_unit"`
}

// Returns one row per ingredient; join in application code to build the full meal.
func (q *Queries) GetMealWithIngredients(ctx context.Context, id int32) ([]GetMealWithIngredientsRow, error) {
	rows, err := q.db.Query(ctx, getMealWithIngredients, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMealWithIngredientsRow
	for rows.Next() {
		var i GetMealWithIngredientsRow
		if err := rows.Scan(
			&i.MealID,
			&i.MealName,
			&i.MealDescription,
			&i.DefaultPortions,
			&i.ShoppingItemID,
			&i.Quantity,
			&i.Unit,
			&i.IngredientName,
			&i.IngredientType,
			&i.PortionsPerUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeals = `-- name: ListMeals :many
SELECT id, name, description, default_portions FROM meals
ORDER BY name
`

func (q *Queries) ListMeals(ctx context.Context) ([]Meal, error) {
	rows, err := q.db.Query(ctx, listMeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DefaultPortions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealsWithIngredientCount = `-- name: ListMealsWithIngredientCount :many
SELECT
    m.id, m.name, m.description, m.default_portions,
    COUNT(mi.shopping_item_id) AS ingredient_count
FROM meals m
LEFT JOIN meal_ingredients mi ON mi.meal_id = m.id
GROUP BY m.id
ORDER BY m.name
`

type ListMealsWithIngredientCountRow struct {
	ID              int32       `json:"id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	DefaultPortions int32       `json:"default_portions"`
	IngredientCount int64       `json:"ingredient_count"`
}

func (q *Queries) ListMealsWithIngredientCount(ctx context.Context) ([]ListMealsWithIngredientCountRow, error) {
	rows, err := q.db.Query(ctx, listMealsWithIngredientCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMealsWithIngredientCountRow
	for rows.Next() {
		var i ListMealsWithIngredientCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DefaultPortions,
			&i.IngredientCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMealIngredient = `-- name: RemoveMealIngredient :exec
DELETE FROM meal_ingredients
WHERE meal_id = $1 AND shopping_item_id = $2
`

type RemoveMealIngredientParams struct {
	MealID         int32 `json:"meal_id"`
	ShoppingItemID int32 `json:"shopping_item_id"`
}

func (q *Queries) RemoveMealIngredient(ctx context.Context, arg RemoveMealIngredientParams) error {
	_, err := q.db.Exec(ctx, removeMealIngredient, arg.MealID, arg.ShoppingItemID)
	return err
}

const updateMeal = `-- name: UpdateMeal :one
UPDATE meals
SET name             = $2,
    description      = $3,
    default_portions = $4
WHERE id = $1
RETURNING id, name, description, default_portions
`

type UpdateMealParams struct {
	ID              int32       `json:"id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	DefaultPortions int32       `json:"default_portions"`
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, updateMeal,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DefaultPortions,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DefaultPortions,
	)
	return i, err
}

const updateMealIngredient = `-- name: UpdateMealIngredient :one
UPDATE meal_ingredients
SET quantity = $3,
    unit     = $4
WHERE meal_id = $1 AND shopping_item_id = $2
RETURNING meal_id, shopping_item_id, quantity, unit
`

type UpdateMealIngredientParams struct {
	MealID         int32          `json:"meal_id"`
	ShoppingItemID int32          `json:"shopping_item_id"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           pgtype.Text    `json:"unit"`
}

func (q *Queries) UpdateMealIngredient(ctx context.Context, arg UpdateMealIngredientParams) (MealIngredient, error) {
	row := q.db.QueryRow(ctx, updateMealIngredient,
		arg.MealID,
		arg.ShoppingItemID,
		arg.Quantity,
		arg.Unit,
	)
	var i MealIngredient
	err := row.Scan(
		&i.MealID,
		&i.ShoppingItemID,
		&i.Quantity,
		&i.Unit,
	)
	return i, err
}
