// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meals.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMealCook = `-- name: AddMealCook :exec
INSERT INTO meal_cooks (meal_id, user_id, household_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddMealCookParams struct {
	MealID      int32       `json:"meal_id"`
	UserID      int32       `json:"user_id"`
	HouseholdID pgtype.Int4 `json:"household_id"`
}

// Assign a cook to a meal, optionally scoped to a specific household.
// Pass NULL for household_id to create a cross-household assignment.
func (q *Queries) AddMealCook(ctx context.Context, arg AddMealCookParams) error {
	_, err := q.db.Exec(ctx, addMealCook, arg.MealID, arg.UserID, arg.HouseholdID)
	return err
}

const addMealIngredient = `-- name: AddMealIngredient :one
INSERT INTO meal_ingredients (meal_id, shopping_item_id, quantity, unit)
VALUES ($1, $2, $3, $4)
RETURNING meal_id, shopping_item_id, quantity, unit
`

type AddMealIngredientParams struct {
	MealID         int32          `json:"meal_id"`
	ShoppingItemID int32          `json:"shopping_item_id"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           pgtype.Text    `json:"unit"`
}

func (q *Queries) AddMealIngredient(ctx context.Context, arg AddMealIngredientParams) (MealIngredient, error) {
	row := q.db.QueryRow(ctx, addMealIngredient,
		arg.MealID,
		arg.ShoppingItemID,
		arg.Quantity,
		arg.Unit,
	)
	var i MealIngredient
	err := row.Scan(
		&i.MealID,
		&i.ShoppingItemID,
		&i.Quantity,
		&i.Unit,
	)
	return i, err
}

const clearMealPlanDay = `-- name: ClearMealPlanDay :exec
DELETE FROM meal_plan
WHERE day_name = $1
  AND (household_id = $2 OR user_id = $3)
`

type ClearMealPlanDayParams struct {
	DayName     string      `json:"day_name"`
	HouseholdID pgtype.Int4 `json:"household_id"`
	UserID      pgtype.Int4 `json:"user_id"`
}

func (q *Queries) ClearMealPlanDay(ctx context.Context, arg ClearMealPlanDayParams) error {
	_, err := q.db.Exec(ctx, clearMealPlanDay, arg.DayName, arg.HouseholdID, arg.UserID)
	return err
}

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (name, description, default_portions, season, household_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, default_portions, season, household_id
`

type CreateMealParams struct {
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	DefaultPortions int32       `json:"default_portions"`
	Season          NullSeason  `json:"season"`
	HouseholdID     pgtype.Int4 `json:"household_id"`
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, createMeal,
		arg.Name,
		arg.Description,
		arg.DefaultPortions,
		arg.Season,
		arg.HouseholdID,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DefaultPortions,
		&i.Season,
		&i.HouseholdID,
	)
	return i, err
}

const deleteMeal = `-- name: DeleteMeal :exec
DELETE FROM meals
WHERE id = $1
`

func (q *Queries) DeleteMeal(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMeal, id)
	return err
}

const getMeal = `-- name: GetMeal :one
SELECT id, name, description, default_portions, season, household_id FROM meals
WHERE id = $1
`

func (q *Queries) GetMeal(ctx context.Context, id int32) (Meal, error) {
	row := q.db.QueryRow(ctx, getMeal, id)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DefaultPortions,
		&i.Season,
		&i.HouseholdID,
	)
	return i, err
}

const getMealCooks = `-- name: GetMealCooks :many
SELECT
    u.id,
    u.name,
    u.username,
    mc.household_id,
    h.name AS household_name
FROM meal_cooks mc
JOIN users u       ON u.id = mc.user_id
LEFT JOIN households h ON h.household_id = mc.household_id
WHERE mc.meal_id = $1
ORDER BY u.name
`

type GetMealCooksRow struct {
	ID            int32       `json:"id"`
	Name          string      `json:"name"`
	Username      string      `json:"username"`
	HouseholdID   pgtype.Int4 `json:"household_id"`
	HouseholdName pgtype.Text `json:"household_name"`
}

// Returns all cook assignments for a meal, with their household scope.
func (q *Queries) GetMealCooks(ctx context.Context, mealID int32) ([]GetMealCooksRow, error) {
	rows, err := q.db.Query(ctx, getMealCooks, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMealCooksRow
	for rows.Next() {
		var i GetMealCooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.HouseholdID,
			&i.HouseholdName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMealPlanFull = `-- name: GetMealPlanFull :many
SELECT
    mp.id,
    mp.day_name,
    mp.meal_id,
    mp.cook_user_id,
    mp.updated_at,
    m.name            AS meal_name,
    m.default_portions,
    m.description     AS meal_description,
    m.season          AS meal_season,
    cu.name           AS cook_name,
    cu.username       AS cook_username
FROM meal_plan mp
LEFT JOIN meals m ON m.id = mp.meal_id
LEFT JOIN users cu ON cu.id = mp.cook_user_id
WHERE mp.household_id = $1 OR mp.user_id = $2
ORDER BY CASE mp.day_name
    WHEN 'Monday' THEN 1 WHEN 'Tuesday' THEN 2 WHEN 'Wednesday' THEN 3
    WHEN 'Thursday' THEN 4 WHEN 'Friday' THEN 5 WHEN 'Saturday' THEN 6
    WHEN 'Sunday' THEN 7 ELSE 8 END
`

type GetMealPlanFullParams struct {
	HouseholdID pgtype.Int4 `json:"household_id"`
	UserID      pgtype.Int4 `json:"user_id"`
}

type GetMealPlanFullRow struct {
	ID              int32            `json:"id"`
	DayName         string           `json:"day_name"`
	MealID          pgtype.Int4      `json:"meal_id"`
	CookUserID      pgtype.Int4      `json:"cook_user_id"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	MealName        pgtype.Text      `json:"meal_name"`
	DefaultPortions pgtype.Int4      `json:"default_portions"`
	MealDescription pgtype.Text      `json:"meal_description"`
	MealSeason      NullSeason       `json:"meal_season"`
	CookName        pgtype.Text      `json:"cook_name"`
	CookUsername    pgtype.Text      `json:"cook_username"`
}

// Returns the week plan with full meal details joined in.
func (q *Queries) GetMealPlanFull(ctx context.Context, arg GetMealPlanFullParams) ([]GetMealPlanFullRow, error) {
	rows, err := q.db.Query(ctx, getMealPlanFull, arg.HouseholdID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMealPlanFullRow
	for rows.Next() {
		var i GetMealPlanFullRow
		if err := rows.Scan(
			&i.ID,
			&i.DayName,
			&i.MealID,
			&i.CookUserID,
			&i.UpdatedAt,
			&i.MealName,
			&i.DefaultPortions,
			&i.MealDescription,
			&i.MealSeason,
			&i.CookName,
			&i.CookUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMealWithIngredients = `-- name: GetMealWithIngredients :many
SELECT
    m.id              AS meal_id,
    m.name            AS meal_name,
    m.description     AS meal_description,
    m.default_portions,
    m.season,
    mi.shopping_item_id,
    mi.quantity,
    mi.unit,
    si.name           AS ingredient_name,
    si.item_type      AS ingredient_type,
    si.portions_per_unit
FROM meals m
JOIN meal_ingredients mi ON mi.meal_id = m.id
JOIN shopping_items si   ON si.id = mi.shopping_item_id
WHERE m.id = $1
ORDER BY si.name
`

type GetMealWithIngredientsRow struct {
	MealID          int32            `json:"meal_id"`
	MealName        string           `json:"meal_name"`
	MealDescription pgtype.Text      `json:"meal_description"`
	DefaultPortions int32            `json:"default_portions"`
	Season          NullSeason       `json:"season"`
	ShoppingItemID  int32            `json:"shopping_item_id"`
	Quantity        pgtype.Numeric   `json:"quantity"`
	Unit            pgtype.Text      `json:"unit"`
	IngredientName  string           `json:"ingredient_name"`
	IngredientType  ShoppingItemType `json:"ingredient_type"`
	PortionsPerUnit int32            `json:"portions_per_unit"`
}

// Returns one row per ingredient; join in application code to build the full meal.
func (q *Queries) GetMealWithIngredients(ctx context.Context, id int32) ([]GetMealWithIngredientsRow, error) {
	rows, err := q.db.Query(ctx, getMealWithIngredients, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMealWithIngredientsRow
	for rows.Next() {
		var i GetMealWithIngredientsRow
		if err := rows.Scan(
			&i.MealID,
			&i.MealName,
			&i.MealDescription,
			&i.DefaultPortions,
			&i.Season,
			&i.ShoppingItemID,
			&i.Quantity,
			&i.Unit,
			&i.IngredientName,
			&i.IngredientType,
			&i.PortionsPerUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMealsForCook = `-- name: GetMealsForCook :many
SELECT m.id, m.name, m.description, m.default_portions, m.season, m.household_id
FROM meals m
WHERE
    -- Respect household-specific meals: only show them to the right household
    (m.household_id IS NULL OR m.household_id = $2)
    AND
    (
        -- Assigned to this user for this specific household
        EXISTS (
            SELECT 1 FROM meal_cooks mc
            WHERE mc.meal_id = m.id
              AND mc.user_id = $1
              AND mc.household_id = $2
        )
        OR
        -- Assigned to this user with no household restriction
        EXISTS (
            SELECT 1 FROM meal_cooks mc
            WHERE mc.meal_id = m.id
              AND mc.user_id = $1
              AND mc.household_id IS NULL
        )
        OR
        -- No cook assigned at all (available to everyone)
        NOT EXISTS (SELECT 1 FROM meal_cooks mc WHERE mc.meal_id = m.id)
    )
ORDER BY m.name
`

type GetMealsForCookParams struct {
	UserID      int32       `json:"user_id"`
	HouseholdID pgtype.Int4 `json:"household_id"`
}

// Meals that a specific user can cook within a given household context:
//  1. Meal is assigned to this user with this exact household_id, OR
//  2. Meal is assigned to this user with no household restriction (NULL), OR
//  3. Meal has no cook assignments at all (universally available).
//
// Additionally, household-specific meals are filtered: if a meal has a
// household_id set, it is only returned when the caller's household matches.
func (q *Queries) GetMealsForCook(ctx context.Context, arg GetMealsForCookParams) ([]Meal, error) {
	rows, err := q.db.Query(ctx, getMealsForCook, arg.UserID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DefaultPortions,
			&i.Season,
			&i.HouseholdID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeals = `-- name: ListMeals :many
SELECT id, name, description, default_portions, season, household_id FROM meals
WHERE household_id IS NULL
   OR household_id = $1
ORDER BY name
`

// Lists all global meals plus meals belonging to the given household.
// Pass NULL for household_id to get only global meals.
func (q *Queries) ListMeals(ctx context.Context, householdID pgtype.Int4) ([]Meal, error) {
	rows, err := q.db.Query(ctx, listMeals, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DefaultPortions,
			&i.Season,
			&i.HouseholdID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealsWithIngredientCount = `-- name: ListMealsWithIngredientCount :many
SELECT
    m.id, m.name, m.description, m.default_portions, m.season, m.household_id,
    COUNT(mi.shopping_item_id) AS ingredient_count
FROM meals m
LEFT JOIN meal_ingredients mi ON mi.meal_id = m.id
WHERE m.household_id IS NULL
   OR m.household_id = $1
GROUP BY m.id
ORDER BY m.name
`

type ListMealsWithIngredientCountRow struct {
	ID              int32       `json:"id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	DefaultPortions int32       `json:"default_portions"`
	Season          NullSeason  `json:"season"`
	HouseholdID     pgtype.Int4 `json:"household_id"`
	IngredientCount int64       `json:"ingredient_count"`
}

// Lists all global meals plus meals belonging to the given household.
func (q *Queries) ListMealsWithIngredientCount(ctx context.Context, householdID pgtype.Int4) ([]ListMealsWithIngredientCountRow, error) {
	rows, err := q.db.Query(ctx, listMealsWithIngredientCount, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMealsWithIngredientCountRow
	for rows.Next() {
		var i ListMealsWithIngredientCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DefaultPortions,
			&i.Season,
			&i.HouseholdID,
			&i.IngredientCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMealCook = `-- name: RemoveMealCook :exec
DELETE FROM meal_cooks
WHERE meal_id = $1 AND user_id = $2
  AND (
      (household_id IS NULL     AND $3::INT IS NULL) OR
      (household_id IS NOT NULL AND household_id = $3)
  )
`

type RemoveMealCookParams struct {
	MealID  int32 `json:"meal_id"`
	UserID  int32 `json:"user_id"`
	Column3 int32 `json:"column_3"`
}

// Remove a cook assignment. household_id must match exactly (NULL removes the
// cross-household assignment; a specific ID removes that household's assignment).
func (q *Queries) RemoveMealCook(ctx context.Context, arg RemoveMealCookParams) error {
	_, err := q.db.Exec(ctx, removeMealCook, arg.MealID, arg.UserID, arg.Column3)
	return err
}

const removeMealIngredient = `-- name: RemoveMealIngredient :exec
DELETE FROM meal_ingredients
WHERE meal_id = $1 AND shopping_item_id = $2
`

type RemoveMealIngredientParams struct {
	MealID         int32 `json:"meal_id"`
	ShoppingItemID int32 `json:"shopping_item_id"`
}

func (q *Queries) RemoveMealIngredient(ctx context.Context, arg RemoveMealIngredientParams) error {
	_, err := q.db.Exec(ctx, removeMealIngredient, arg.MealID, arg.ShoppingItemID)
	return err
}

const setMealPlanDay = `-- name: SetMealPlanDay :one
INSERT INTO meal_plan (day_name, meal_id, cook_user_id, household_id, user_id, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (day_name, household_id, user_id)
DO UPDATE SET
    meal_id      = EXCLUDED.meal_id,
    cook_user_id = EXCLUDED.cook_user_id,
    updated_at   = now()
RETURNING id, day_name, week_start, meal_name, household_id, user_id, updated_at, meal_id, cook_user_id, repeating_cook_user_id, temp_cook_user_id, repeating_meal_id, temp_meal_id
`

type SetMealPlanDayParams struct {
	DayName     string      `json:"day_name"`
	MealID      pgtype.Int4 `json:"meal_id"`
	CookUserID  pgtype.Int4 `json:"cook_user_id"`
	HouseholdID pgtype.Int4 `json:"household_id"`
	UserID      pgtype.Int4 `json:"user_id"`
}

func (q *Queries) SetMealPlanDay(ctx context.Context, arg SetMealPlanDayParams) (MealPlan, error) {
	row := q.db.QueryRow(ctx, setMealPlanDay,
		arg.DayName,
		arg.MealID,
		arg.CookUserID,
		arg.HouseholdID,
		arg.UserID,
	)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.DayName,
		&i.WeekStart,
		&i.MealName,
		&i.HouseholdID,
		&i.UserID,
		&i.UpdatedAt,
		&i.MealID,
		&i.CookUserID,
		&i.RepeatingCookUserID,
		&i.TempCookUserID,
		&i.RepeatingMealID,
		&i.TempMealID,
	)
	return i, err
}

const updateMeal = `-- name: UpdateMeal :one
UPDATE meals
SET name             = $2,
    description      = $3,
    default_portions = $4,
    season           = $5,
    household_id     = $6
WHERE id = $1
RETURNING id, name, description, default_portions, season, household_id
`

type UpdateMealParams struct {
	ID              int32       `json:"id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	DefaultPortions int32       `json:"default_portions"`
	Season          NullSeason  `json:"season"`
	HouseholdID     pgtype.Int4 `json:"household_id"`
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, updateMeal,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DefaultPortions,
		arg.Season,
		arg.HouseholdID,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DefaultPortions,
		&i.Season,
		&i.HouseholdID,
	)
	return i, err
}

const updateMealIngredient = `-- name: UpdateMealIngredient :one
UPDATE meal_ingredients
SET quantity = $3,
    unit     = $4
WHERE meal_id = $1 AND shopping_item_id = $2
RETURNING meal_id, shopping_item_id, quantity, unit
`

type UpdateMealIngredientParams struct {
	MealID         int32          `json:"meal_id"`
	ShoppingItemID int32          `json:"shopping_item_id"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           pgtype.Text    `json:"unit"`
}

func (q *Queries) UpdateMealIngredient(ctx context.Context, arg UpdateMealIngredientParams) (MealIngredient, error) {
	row := q.db.QueryRow(ctx, updateMealIngredient,
		arg.MealID,
		arg.ShoppingItemID,
		arg.Quantity,
		arg.Unit,
	)
	var i MealIngredient
	err := row.Scan(
		&i.MealID,
		&i.ShoppingItemID,
		&i.Quantity,
		&i.Unit,
	)
	return i, err
}
