// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meal_components.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMealComponent = `-- name: AddMealComponent :exec
INSERT INTO meal_components (parent_meal_id, sub_meal_id, sort_order)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddMealComponentParams struct {
	ParentMealID int32 `json:"parent_meal_id"`
	SubMealID    int32 `json:"sub_meal_id"`
	SortOrder    int32 `json:"sort_order"`
}

func (q *Queries) AddMealComponent(ctx context.Context, arg AddMealComponentParams) error {
	_, err := q.db.Exec(ctx, addMealComponent, arg.ParentMealID, arg.SubMealID, arg.SortOrder)
	return err
}

const getMealComponents = `-- name: GetMealComponents :many
SELECT
    mc.sort_order,
    m.id,
    m.name,
    m.description,
    m.default_portions
FROM meal_components mc
JOIN meals m ON m.id = mc.sub_meal_id
WHERE mc.parent_meal_id = $1
ORDER BY mc.sort_order, m.name
`

type GetMealComponentsRow struct {
	SortOrder       int32       `json:"sort_order"`
	ID              int32       `json:"id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	DefaultPortions int32       `json:"default_portions"`
}

// Sub-meals that make up a composite meal, with full meal details.
func (q *Queries) GetMealComponents(ctx context.Context, parentMealID int32) ([]GetMealComponentsRow, error) {
	rows, err := q.db.Query(ctx, getMealComponents, parentMealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMealComponentsRow
	for rows.Next() {
		var i GetMealComponentsRow
		if err := rows.Scan(
			&i.SortOrder,
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DefaultPortions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParentMeals = `-- name: GetParentMeals :many
SELECT
    mc.parent_meal_id,
    m.name AS parent_name
FROM meal_components mc
JOIN meals m ON m.id = mc.parent_meal_id
WHERE mc.sub_meal_id = $1
`

type GetParentMealsRow struct {
	ParentMealID int32  `json:"parent_meal_id"`
	ParentName   string `json:"parent_name"`
}

// Which composite meals use this meal as a component?
func (q *Queries) GetParentMeals(ctx context.Context, subMealID int32) ([]GetParentMealsRow, error) {
	rows, err := q.db.Query(ctx, getParentMeals, subMealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetParentMealsRow
	for rows.Next() {
		var i GetParentMealsRow
		if err := rows.Scan(&i.ParentMealID, &i.ParentName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMealComponent = `-- name: RemoveMealComponent :exec
DELETE FROM meal_components
WHERE parent_meal_id = $1 AND sub_meal_id = $2
`

type RemoveMealComponentParams struct {
	ParentMealID int32 `json:"parent_meal_id"`
	SubMealID    int32 `json:"sub_meal_id"`
}

func (q *Queries) RemoveMealComponent(ctx context.Context, arg RemoveMealComponentParams) error {
	_, err := q.db.Exec(ctx, removeMealComponent, arg.ParentMealID, arg.SubMealID)
	return err
}

const updateShoppingItemShelfLife = `-- name: UpdateShoppingItemShelfLife :one
UPDATE shopping_items
SET shelf_life_days = $2
WHERE id = $1
RETURNING id, name, item_type, text_id, portions_per_unit, shelf_life_days
`

type UpdateShoppingItemShelfLifeParams struct {
	ID            int32       `json:"id"`
	ShelfLifeDays pgtype.Int4 `json:"shelf_life_days"`
}

func (q *Queries) UpdateShoppingItemShelfLife(ctx context.Context, arg UpdateShoppingItemShelfLifeParams) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, updateShoppingItemShelfLife, arg.ID, arg.ShelfLifeDays)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ItemType,
		&i.TextID,
		&i.PortionsPerUnit,
		&i.ShelfLifeDays,
	)
	return i, err
}
