// Code generated by sqlc. DO NOT EDIT.
// source: meal_components.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMealComponent = `
INSERT INTO meal_components (parent_meal_id, sub_meal_id, sort_order)
VALUES ($1, $2, $3) ON CONFLICT DO NOTHING`

func (q *Queries) AddMealComponent(ctx context.Context, parentID, subID int32, sortOrder int32) error {
	_, err := q.db.Exec(ctx, addMealComponent, parentID, subID, sortOrder)
	return err
}

const removeMealComponent = `DELETE FROM meal_components WHERE parent_meal_id = $1 AND sub_meal_id = $2`

func (q *Queries) RemoveMealComponent(ctx context.Context, parentID, subID int32) error {
	_, err := q.db.Exec(ctx, removeMealComponent, parentID, subID)
	return err
}

const getMealComponents = `
SELECT mc.sort_order, m.id, m.name, m.description, m.default_portions
FROM meal_components mc
JOIN meals m ON m.id = mc.sub_meal_id
WHERE mc.parent_meal_id = $1
ORDER BY mc.sort_order, m.name`

type MealComponentRow struct {
	SortOrder       int32       `json:"sort_order"`
	ID              int32       `json:"id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	DefaultPortions int32       `json:"default_portions"`
}

func (q *Queries) GetMealComponents(ctx context.Context, parentID int32) ([]MealComponentRow, error) {
	rows, err := q.db.Query(ctx, getMealComponents, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MealComponentRow
	for rows.Next() {
		var i MealComponentRow
		if err := rows.Scan(&i.SortOrder, &i.ID, &i.Name, &i.Description, &i.DefaultPortions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getParentMeals = `
SELECT mc.parent_meal_id, m.name AS parent_name
FROM meal_components mc
JOIN meals m ON m.id = mc.parent_meal_id
WHERE mc.sub_meal_id = $1`

type ParentMealRow struct {
	ParentMealID int32  `json:"parent_meal_id"`
	ParentName   string `json:"parent_name"`
}

func (q *Queries) GetParentMeals(ctx context.Context, subID int32) ([]ParentMealRow, error) {
	rows, err := q.db.Query(ctx, getParentMeals, subID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParentMealRow
	for rows.Next() {
		var i ParentMealRow
		if err := rows.Scan(&i.ParentMealID, &i.ParentName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateShelfLife = `UPDATE shopping_items SET shelf_life_days = $2 WHERE id = $1 RETURNING id, name, item_type, text_id, portions_per_unit, shelf_life_days`

func (q *Queries) UpdateShoppingItemShelfLife(ctx context.Context, itemID int32, days pgtype.Int4) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, updateShelfLife, itemID, days)
	var i ShoppingItem
	err := row.Scan(&i.ID, &i.Name, &i.ItemType, &i.TextID, &i.PortionsPerUnit, &i.ShelfLifeDays)
	return i, err
}
