// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meal_photos.sql

package database

import (
	"context"
)

const getMealPhoto = `-- name: GetMealPhoto :one
SELECT content_type, bytes FROM meal_photos WHERE id = $1
`

type GetMealPhotoRow struct {
	ContentType string `json:"content_type"`
	Bytes       []byte `json:"bytes"`
}

func (q *Queries) GetMealPhoto(ctx context.Context, id string) (GetMealPhotoRow, error) {
	row := q.db.QueryRow(ctx, getMealPhoto, id)
	var i GetMealPhotoRow
	err := row.Scan(&i.ContentType, &i.Bytes)
	return i, err
}

const upsertMealPhoto = `-- name: UpsertMealPhoto :exec
INSERT INTO meal_photos (id, content_type, bytes, byte_size)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO NOTHING
`

type UpsertMealPhotoParams struct {
	ID          string `json:"id"`
	ContentType string `json:"content_type"`
	Bytes       []byte `json:"bytes"`
	ByteSize    int32  `json:"byte_size"`
}

// Store an uploaded photo content-addressed by its SHA-256. Idempotent: the same
// image uploaded twice keeps the single existing row.
func (q *Queries) UpsertMealPhoto(ctx context.Context, arg UpsertMealPhotoParams) error {
	_, err := q.db.Exec(ctx, upsertMealPhoto,
		arg.ID,
		arg.ContentType,
		arg.Bytes,
		arg.ByteSize,
	)
	return err
}
