// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Season string

const (
	SeasonSpring Season = "spring"
	SeasonSummer Season = "summer"
	SeasonAutumn Season = "autumn"
	SeasonWinter Season = "winter"
)

func (e *Season) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Season(s)
	case string:
		*e = Season(s)
	default:
		return fmt.Errorf("unsupported scan type for Season: %T", src)
	}
	return nil
}

type NullSeason struct {
	Season Season `json:"season"`
	Valid  bool   `json:"valid"` // Valid is true if Season is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSeason) Scan(value interface{}) error {
	if value == nil {
		ns.Season, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Season.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSeason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Season), nil
}

type ShoppingItemType string

const (
	ShoppingItemTypeFruit      ShoppingItemType = "fruit"
	ShoppingItemTypeVegetable  ShoppingItemType = "vegetable"
	ShoppingItemTypeDairy      ShoppingItemType = "dairy"
	ShoppingItemTypeMeat       ShoppingItemType = "meat"
	ShoppingItemTypeMeatFree   ShoppingItemType = "meat_free"
	ShoppingItemTypeSeafood    ShoppingItemType = "seafood"
	ShoppingItemTypeBakery     ShoppingItemType = "bakery"
	ShoppingItemTypePantry     ShoppingItemType = "pantry"
	ShoppingItemTypeSnacks     ShoppingItemType = "snacks"
	ShoppingItemTypeFrozen     ShoppingItemType = "frozen"
	ShoppingItemTypeDrinks     ShoppingItemType = "drinks"
	ShoppingItemTypeCleaning   ShoppingItemType = "cleaning"
	ShoppingItemTypeToiletries ShoppingItemType = "toiletries"
	ShoppingItemTypeBaby       ShoppingItemType = "baby"
	ShoppingItemTypeHealth     ShoppingItemType = "health"
	ShoppingItemTypeHousehold  ShoppingItemType = "household"
	ShoppingItemTypeSpices     ShoppingItemType = "spices"
	ShoppingItemTypeCondiments ShoppingItemType = "condiments"
)

func (e *ShoppingItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShoppingItemType(s)
	case string:
		*e = ShoppingItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for ShoppingItemType: %T", src)
	}
	return nil
}

type NullShoppingItemType struct {
	ShoppingItemType ShoppingItemType `json:"shopping_item_type"`
	Valid            bool             `json:"valid"` // Valid is true if ShoppingItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShoppingItemType) Scan(value interface{}) error {
	if value == nil {
		ns.ShoppingItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShoppingItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShoppingItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShoppingItemType), nil
}

type Household struct {
	HouseholdID int32       `json:"household_id"`
	NumPeople   int32       `json:"num_people"`
	Name        pgtype.Text `json:"name"`
}

type HouseholdInvite struct {
	ID                int32            `json:"id"`
	HouseholdID       int32            `json:"household_id"`
	InviteCode        string           `json:"invite_code"`
	RequestedByUserID int32            `json:"requested_by_user_id"`
	Status            string           `json:"status"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type HouseholdMember struct {
	HouseholdID int32 `json:"household_id"`
	UserID      int32 `json:"user_id"`
}

type Meal struct {
	ID              int32       `json:"id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	DefaultPortions int32       `json:"default_portions"`
	Season          NullSeason  `json:"season"`
	HouseholdID     pgtype.Int4 `json:"household_id"`
}

type MealComponent struct {
	ParentMealID int32 `json:"parent_meal_id"`
	SubMealID    int32 `json:"sub_meal_id"`
	SortOrder    int32 `json:"sort_order"`
}

type MealCook struct {
	ID          int32       `json:"id"`
	MealID      int32       `json:"meal_id"`
	UserID      int32       `json:"user_id"`
	HouseholdID pgtype.Int4 `json:"household_id"`
}

type MealIngredient struct {
	MealID         int32          `json:"meal_id"`
	ShoppingItemID int32          `json:"shopping_item_id"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           pgtype.Text    `json:"unit"`
}

type MealOptionGroupEntry struct {
	ID             int32       `json:"id"`
	MealID         int32       `json:"meal_id"`
	OptionGroup    string      `json:"option_group"`
	OptionType     string      `json:"option_type"`
	SortOrder      int32       `json:"sort_order"`
	ShoppingItemID pgtype.Int4 `json:"shopping_item_id"`
	SubMealID      pgtype.Int4 `json:"sub_meal_id"`
}

type MealPlan struct {
	ID      int32  `json:"id"`
	DayName string `json:"day_name"`
	// Monday of the ISO week this plan row belongs to
	WeekStart   pgtype.Date      `json:"week_start"`
	MealName    pgtype.Text      `json:"meal_name"`
	HouseholdID pgtype.Int4      `json:"household_id"`
	UserID      pgtype.Int4      `json:"user_id"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	MealID      pgtype.Int4      `json:"meal_id"`
	CookUserID  pgtype.Int4      `json:"cook_user_id"`
	// Person who cooks on this weekday every week (standing assignment)
	RepeatingCookUserID pgtype.Int4 `json:"repeating_cook_user_id"`
	// One-off cook override for the next occurrence; cleared after the week rolls over
	TempCookUserID pgtype.Int4 `json:"temp_cook_user_id"`
	// Meal served on this weekday every week (standing assignment)
	RepeatingMealID pgtype.Int4 `json:"repeating_meal_id"`
	// One-off meal override for the next occurrence; cleared after the week rolls over
	TempMealID pgtype.Int4 `json:"temp_meal_id"`
}

type Pantry struct {
	ID                int32            `json:"id"`
	ShoppingItemID    int32            `json:"shopping_item_id"`
	HouseholdID       pgtype.Int4      `json:"household_id"`
	UserID            pgtype.Int4      `json:"user_id"`
	PortionsRemaining pgtype.Numeric   `json:"portions_remaining"`
	ExpiresOn         pgtype.Date      `json:"expires_on"`
	Status            string           `json:"status"`
	BoughtAt          pgtype.Timestamp `json:"bought_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type ShoppingItem struct {
	ID              int32            `json:"id"`
	Name            string           `json:"name"`
	ItemType        ShoppingItemType `json:"item_type"`
	TextID          pgtype.Text      `json:"text_id"`
	PortionsPerUnit int32            `json:"portions_per_unit"`
	ShelfLifeDays   pgtype.Int4      `json:"shelf_life_days"`
}

type ShoppingList struct {
	ID             int32            `json:"id"`
	ShoppingItemID int32            `json:"shopping_item_id"`
	Quantity       int32            `json:"quantity"`
	HouseholdID    pgtype.Int4      `json:"household_id"`
	UserID         pgtype.Int4      `json:"user_id"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type ShoppingListHaveIt struct {
	ID             int32            `json:"id"`
	ShoppingItemID int32            `json:"shopping_item_id"`
	HouseholdID    pgtype.Int4      `json:"household_id"`
	UserID         pgtype.Int4      `json:"user_id"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID           int32            `json:"id"`
	Name         string           `json:"name"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
