// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ShoppingItemType string

const (
	ShoppingItemTypeFruit      ShoppingItemType = "fruit"
	ShoppingItemTypeVegetable  ShoppingItemType = "vegetable"
	ShoppingItemTypeDairy      ShoppingItemType = "dairy"
	ShoppingItemTypeMeat       ShoppingItemType = "meat"
	ShoppingItemTypeMeatFree   ShoppingItemType = "meat_free"
	ShoppingItemTypeSeafood    ShoppingItemType = "seafood"
	ShoppingItemTypeBakery     ShoppingItemType = "bakery"
	ShoppingItemTypePantry     ShoppingItemType = "pantry"
	ShoppingItemTypeSnacks     ShoppingItemType = "snacks"
	ShoppingItemTypeFrozen     ShoppingItemType = "frozen"
	ShoppingItemTypeDrinks     ShoppingItemType = "drinks"
	ShoppingItemTypeCleaning   ShoppingItemType = "cleaning"
	ShoppingItemTypeToiletries ShoppingItemType = "toiletries"
	ShoppingItemTypeBaby       ShoppingItemType = "baby"
	ShoppingItemTypeHealth     ShoppingItemType = "health"
	ShoppingItemTypeHousehold  ShoppingItemType = "household"
	ShoppingItemTypeSpices     ShoppingItemType = "spices"
	ShoppingItemTypeCondiments ShoppingItemType = "condiments"
)

func (e *ShoppingItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShoppingItemType(s)
	case string:
		*e = ShoppingItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for ShoppingItemType: %T", src)
	}
	return nil
}

type NullShoppingItemType struct {
	ShoppingItemType ShoppingItemType `json:"shopping_item_type"`
	Valid            bool             `json:"valid"` // Valid is true if ShoppingItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShoppingItemType) Scan(value interface{}) error {
	if value == nil {
		ns.ShoppingItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShoppingItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShoppingItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShoppingItemType), nil
}

type Household struct {
	HouseholdID int32 `json:"household_id"`
	NumPeople   int32 `json:"num_people"`
}

type HouseholdMember struct {
	HouseholdID int32 `json:"household_id"`
	UserID      int32 `json:"user_id"`
}

type Meal struct {
	ID              int32       `json:"id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	DefaultPortions int32       `json:"default_portions"`
}

type MealIngredient struct {
	MealID         int32          `json:"meal_id"`
	ShoppingItemID int32          `json:"shopping_item_id"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           pgtype.Text    `json:"unit"`
}

type ShoppingItem struct {
	ID              int32            `json:"id"`
	Name            string           `json:"name"`
	ItemType        ShoppingItemType `json:"item_type"`
	TextID          pgtype.Text      `json:"text_id"`
	PortionsPerUnit int32            `json:"portions_per_unit"`
}

type ShoppingList struct {
	ID             int32       `json:"id"`
	ShoppingItemID int32       `json:"shopping_item_id"`
	Quantity       int32       `json:"quantity"`
	HouseholdID    pgtype.Int4 `json:"household_id"`
	UserID         pgtype.Int4 `json:"user_id"`
}

type User struct {
	ID           int32            `json:"id"`
	Name         string           `json:"name"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
