// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ShoppingItemType string

const (
	ShoppingItemTypeFruit      ShoppingItemType = "fruit"
	ShoppingItemTypeVegetable  ShoppingItemType = "vegetable"
	ShoppingItemTypeDairy      ShoppingItemType = "dairy"
	ShoppingItemTypeMeat       ShoppingItemType = "meat"
	ShoppingItemTypeMeatFree   ShoppingItemType = "meat_free"
	ShoppingItemTypeSeafood    ShoppingItemType = "seafood"
	ShoppingItemTypeBakery     ShoppingItemType = "bakery"
	ShoppingItemTypePantry     ShoppingItemType = "pantry"
	ShoppingItemTypeSnacks     ShoppingItemType = "snacks"
	ShoppingItemTypeFrozen     ShoppingItemType = "frozen"
	ShoppingItemTypeDrinks     ShoppingItemType = "drinks"
	ShoppingItemTypeCleaning   ShoppingItemType = "cleaning"
	ShoppingItemTypeToiletries ShoppingItemType = "toiletries"
	ShoppingItemTypeBaby       ShoppingItemType = "baby"
	ShoppingItemTypeHealth     ShoppingItemType = "health"
	ShoppingItemTypeHousehold  ShoppingItemType = "household"
	ShoppingItemTypeSpices     ShoppingItemType = "spices"
	ShoppingItemTypeCondiments ShoppingItemType = "condiments"
)

func (e *ShoppingItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShoppingItemType(s)
	case string:
		*e = ShoppingItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for ShoppingItemType: %T", src)
	}
	return nil
}

type NullShoppingItemType struct {
	ShoppingItemType ShoppingItemType
	Valid            bool // Valid is true if ShoppingItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShoppingItemType) Scan(value interface{}) error {
	if value == nil {
		ns.ShoppingItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShoppingItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShoppingItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShoppingItemType), nil
}

type Household struct {
	HouseholdID int32
}

type ShoppingItem struct {
	ID       int32
	Name     string
	ItemType ShoppingItemType
}

type ShoppingList struct {
	ShoppingItemID pgtype.Int4
	Quantity       pgtype.Int4
}

type User struct {
	ID        int32
	Name      pgtype.Text
	Household pgtype.Int4
	Username  pgtype.Text
	Password  pgtype.Text
}
