// Code generated by sqlc. DO NOT EDIT.
// source: pantry.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// ── Pantry row ────────────────────────────────────────────────────────────────

type PantryRow struct {
	ID                int32            `json:"id"`
	ShoppingItemID    int32            `json:"shopping_item_id"`
	ItemName          string           `json:"item_name"`
	ItemType          ShoppingItemType `json:"item_type"`
	PortionsPerUnit   int32            `json:"portions_per_unit"`
	ShelfLifeDays     pgtype.Int4      `json:"shelf_life_days"`
	PortionsRemaining pgtype.Numeric   `json:"portions_remaining"`
	ExpiresOn         pgtype.Date      `json:"expires_on"`
	Status            string           `json:"status"`
	BoughtAt          pgtype.Timestamp `json:"bought_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type PantryEntry struct {
	ID                int32            `json:"id"`
	ShoppingItemID    int32            `json:"shopping_item_id"`
	HouseholdID       pgtype.Int4      `json:"household_id"`
	UserID            pgtype.Int4      `json:"user_id"`
	PortionsRemaining pgtype.Numeric   `json:"portions_remaining"`
	ExpiresOn         pgtype.Date      `json:"expires_on"`
	Status            string           `json:"status"`
	BoughtAt          pgtype.Timestamp `json:"bought_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

// ── GetPantry ─────────────────────────────────────────────────────────────────

const getPantry = `
SELECT p.id, p.shopping_item_id, si.name AS item_name, si.item_type,
       si.portions_per_unit, si.shelf_life_days,
       p.portions_remaining, p.expires_on, p.status, p.bought_at, p.updated_at
FROM pantry p
JOIN shopping_items si ON si.id = p.shopping_item_id
WHERE p.household_id = $1 OR p.user_id = $2
ORDER BY p.status DESC, p.expires_on ASC NULLS LAST, si.name`

func (q *Queries) GetPantry(ctx context.Context, arg GetShoppingListParams) ([]PantryRow, error) {
	rows, err := q.db.Query(ctx, getPantry, arg.HouseholdID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PantryRow
	for rows.Next() {
		var i PantryRow
		if err := rows.Scan(&i.ID, &i.ShoppingItemID, &i.ItemName, &i.ItemType,
			&i.PortionsPerUnit, &i.ShelfLifeDays,
			&i.PortionsRemaining, &i.ExpiresOn, &i.Status, &i.BoughtAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

// ── UpsertPantryItem ──────────────────────────────────────────────────────────

const upsertPantryItemHousehold = `
INSERT INTO pantry (shopping_item_id, household_id, user_id, portions_remaining, expires_on, status, updated_at)
VALUES ($1, $2, $3, $4, $5, 'fresh', now())
ON CONFLICT (shopping_item_id, household_id) WHERE household_id IS NOT NULL
DO UPDATE SET
    portions_remaining = pantry.portions_remaining + EXCLUDED.portions_remaining,
    expires_on         = CASE WHEN EXCLUDED.expires_on IS NOT NULL THEN EXCLUDED.expires_on ELSE pantry.expires_on END,
    status             = 'fresh',
    updated_at         = now()
RETURNING id, shopping_item_id, household_id, user_id, portions_remaining, expires_on, status, bought_at, updated_at`

type UpsertPantryParams struct {
	ShoppingItemID    int32          `json:"shopping_item_id"`
	HouseholdID       pgtype.Int4    `json:"household_id"`
	UserID            pgtype.Int4    `json:"user_id"`
	PortionsRemaining pgtype.Numeric `json:"portions_remaining"`
	ExpiresOn         pgtype.Date    `json:"expires_on"`
}

func (q *Queries) UpsertPantryItem(ctx context.Context, arg UpsertPantryParams) (PantryEntry, error) {
	row := q.db.QueryRow(ctx, upsertPantryItemHousehold,
		arg.ShoppingItemID, arg.HouseholdID, arg.UserID, arg.PortionsRemaining, arg.ExpiresOn)
	var i PantryEntry
	err := row.Scan(&i.ID, &i.ShoppingItemID, &i.HouseholdID, &i.UserID,
		&i.PortionsRemaining, &i.ExpiresOn, &i.Status, &i.BoughtAt, &i.UpdatedAt)
	return i, err
}

// ── DecrementPantryPortions ───────────────────────────────────────────────────

const decrementPantryPortions = `
UPDATE pantry
SET portions_remaining = GREATEST(0, portions_remaining - $3),
    updated_at         = now()
WHERE shopping_item_id = $1
  AND (household_id = $2 OR user_id = $4)
RETURNING id, shopping_item_id, household_id, user_id, portions_remaining, expires_on, status, bought_at, updated_at`

type DecrementPantryParams struct {
	ShoppingItemID int32          `json:"shopping_item_id"`
	HouseholdID    pgtype.Int4    `json:"household_id"`
	Decrement      pgtype.Numeric `json:"decrement"`
	UserID         pgtype.Int4    `json:"user_id"`
}

func (q *Queries) DecrementPantryPortions(ctx context.Context, arg DecrementPantryParams) (PantryEntry, error) {
	row := q.db.QueryRow(ctx, decrementPantryPortions,
		arg.ShoppingItemID, arg.HouseholdID, arg.Decrement, arg.UserID)
	var i PantryEntry
	err := row.Scan(&i.ID, &i.ShoppingItemID, &i.HouseholdID, &i.UserID,
		&i.PortionsRemaining, &i.ExpiresOn, &i.Status, &i.BoughtAt, &i.UpdatedAt)
	return i, err
}

// ── RemovePantryItem ──────────────────────────────────────────────────────────

const removePantryItem = `DELETE FROM pantry WHERE id = $1`

func (q *Queries) RemovePantryItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, removePantryItem, id)
	return err
}

// ── ExpirePantryItems (scheduled job) ────────────────────────────────────────

const expirePantryItems = `
UPDATE pantry
SET status     = CASE
                    WHEN expires_on < CURRENT_DATE                        THEN 'expired'
                    WHEN expires_on <= CURRENT_DATE + INTERVAL '2 days'   THEN 'expiring_soon'
                    ELSE status
                 END,
    updated_at = now()
WHERE expires_on IS NOT NULL
  AND status <> 'expired'
RETURNING id, shopping_item_id, household_id, user_id, status, expires_on`

type ExpiredPantryRow struct {
	ID             int32       `json:"id"`
	ShoppingItemID int32       `json:"shopping_item_id"`
	HouseholdID    pgtype.Int4 `json:"household_id"`
	UserID         pgtype.Int4 `json:"user_id"`
	Status         string      `json:"status"`
	ExpiresOn      pgtype.Date `json:"expires_on"`
}

func (q *Queries) ExpirePantryItems(ctx context.Context) ([]ExpiredPantryRow, error) {
	rows, err := q.db.Query(ctx, expirePantryItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpiredPantryRow
	for rows.Next() {
		var i ExpiredPantryRow
		if err := rows.Scan(&i.ID, &i.ShoppingItemID, &i.HouseholdID, &i.UserID, &i.Status, &i.ExpiresOn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
