// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pantry.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decrementPantryPortions = `-- name: DecrementPantryPortions :one
UPDATE pantry
SET portions_remaining = GREATEST(0, portions_remaining - $3),
    updated_at         = now()
WHERE shopping_item_id = $1
  AND (household_id = $2 OR user_id = $4)
RETURNING id, shopping_item_id, household_id, user_id, portions_remaining, expires_on, status, bought_at, updated_at
`

type DecrementPantryPortionsParams struct {
	ShoppingItemID    int32          `json:"shopping_item_id"`
	HouseholdID       pgtype.Int4    `json:"household_id"`
	PortionsRemaining pgtype.Numeric `json:"portions_remaining"`
	UserID            pgtype.Int4    `json:"user_id"`
}

// Called when a meal is cooked. Decrements portions by the given amount.
// Clamps to 0 — never goes negative.
func (q *Queries) DecrementPantryPortions(ctx context.Context, arg DecrementPantryPortionsParams) (Pantry, error) {
	row := q.db.QueryRow(ctx, decrementPantryPortions,
		arg.ShoppingItemID,
		arg.HouseholdID,
		arg.PortionsRemaining,
		arg.UserID,
	)
	var i Pantry
	err := row.Scan(
		&i.ID,
		&i.ShoppingItemID,
		&i.HouseholdID,
		&i.UserID,
		&i.PortionsRemaining,
		&i.ExpiresOn,
		&i.Status,
		&i.BoughtAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expirePantryItems = `-- name: ExpirePantryItems :many
UPDATE pantry
SET status     = CASE
                    WHEN expires_on < CURRENT_DATE                    THEN 'expired'
                    WHEN expires_on <= CURRENT_DATE + INTERVAL '2 days' THEN 'expiring_soon'
                    ELSE status
                 END,
    updated_at = now()
WHERE expires_on IS NOT NULL
  AND status <> 'expired'
RETURNING id, shopping_item_id, household_id, user_id, status, expires_on
`

type ExpirePantryItemsRow struct {
	ID             int32       `json:"id"`
	ShoppingItemID int32       `json:"shopping_item_id"`
	HouseholdID    pgtype.Int4 `json:"household_id"`
	UserID         pgtype.Int4 `json:"user_id"`
	Status         string      `json:"status"`
	ExpiresOn      pgtype.Date `json:"expires_on"`
}

// Called by the scheduled job. Marks items as expiring_soon or expired.
func (q *Queries) ExpirePantryItems(ctx context.Context) ([]ExpirePantryItemsRow, error) {
	rows, err := q.db.Query(ctx, expirePantryItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpirePantryItemsRow
	for rows.Next() {
		var i ExpirePantryItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingItemID,
			&i.HouseholdID,
			&i.UserID,
			&i.Status,
			&i.ExpiresOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredPantryItems = `-- name: GetExpiredPantryItems :many
SELECT p.id, p.shopping_item_id, si.name AS item_name, p.expires_on, p.status,
       p.household_id, p.user_id
FROM pantry p
JOIN shopping_items si ON si.id = p.shopping_item_id
WHERE p.status IN ('expiring_soon', 'expired')
ORDER BY p.expires_on ASC
`

type GetExpiredPantryItemsRow struct {
	ID             int32       `json:"id"`
	ShoppingItemID int32       `json:"shopping_item_id"`
	ItemName       string      `json:"item_name"`
	ExpiresOn      pgtype.Date `json:"expires_on"`
	Status         string      `json:"status"`
	HouseholdID    pgtype.Int4 `json:"household_id"`
	UserID         pgtype.Int4 `json:"user_id"`
}

func (q *Queries) GetExpiredPantryItems(ctx context.Context) ([]GetExpiredPantryItemsRow, error) {
	rows, err := q.db.Query(ctx, getExpiredPantryItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredPantryItemsRow
	for rows.Next() {
		var i GetExpiredPantryItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingItemID,
			&i.ItemName,
			&i.ExpiresOn,
			&i.Status,
			&i.HouseholdID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPantry = `-- name: GetPantry :many
SELECT
    p.id,
    p.shopping_item_id,
    si.name             AS item_name,
    si.item_type,
    si.portions_per_unit,
    si.shelf_life_days,
    p.portions_remaining,
    p.expires_on,
    p.status,
    p.bought_at,
    p.updated_at
FROM pantry p
JOIN shopping_items si ON si.id = p.shopping_item_id
WHERE p.household_id = $1 OR p.user_id = $2
ORDER BY p.status DESC, p.expires_on ASC NULLS LAST, si.name
`

type GetPantryParams struct {
	HouseholdID pgtype.Int4 `json:"household_id"`
	UserID      pgtype.Int4 `json:"user_id"`
}

type GetPantryRow struct {
	ID                int32            `json:"id"`
	ShoppingItemID    int32            `json:"shopping_item_id"`
	ItemName          string           `json:"item_name"`
	ItemType          ShoppingItemType `json:"item_type"`
	PortionsPerUnit   int32            `json:"portions_per_unit"`
	ShelfLifeDays     pgtype.Int4      `json:"shelf_life_days"`
	PortionsRemaining pgtype.Numeric   `json:"portions_remaining"`
	ExpiresOn         pgtype.Date      `json:"expires_on"`
	Status            string           `json:"status"`
	BoughtAt          pgtype.Timestamp `json:"bought_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

// Returns all pantry entries for a user/household, joined with item details.
func (q *Queries) GetPantry(ctx context.Context, arg GetPantryParams) ([]GetPantryRow, error) {
	rows, err := q.db.Query(ctx, getPantry, arg.HouseholdID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPantryRow
	for rows.Next() {
		var i GetPantryRow
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingItemID,
			&i.ItemName,
			&i.ItemType,
			&i.PortionsPerUnit,
			&i.ShelfLifeDays,
			&i.PortionsRemaining,
			&i.ExpiresOn,
			&i.Status,
			&i.BoughtAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePantryItem = `-- name: RemovePantryItem :exec
DELETE FROM pantry WHERE id = $1
`

func (q *Queries) RemovePantryItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, removePantryItem, id)
	return err
}

const upsertPantryItem = `-- name: UpsertPantryItem :one
INSERT INTO pantry (shopping_item_id, household_id, user_id, portions_remaining, expires_on, status, updated_at)
VALUES ($1, $2, $3, $4, $5, 'fresh', now())
ON CONFLICT (shopping_item_id, household_id) WHERE household_id IS NOT NULL
DO UPDATE SET
    portions_remaining = pantry.portions_remaining + EXCLUDED.portions_remaining,
    expires_on         = CASE WHEN EXCLUDED.expires_on IS NOT NULL THEN EXCLUDED.expires_on ELSE pantry.expires_on END,
    status             = 'fresh',
    updated_at         = now()
RETURNING id, shopping_item_id, household_id, user_id, portions_remaining, expires_on, status, bought_at, updated_at
`

type UpsertPantryItemParams struct {
	ShoppingItemID    int32          `json:"shopping_item_id"`
	HouseholdID       pgtype.Int4    `json:"household_id"`
	UserID            pgtype.Int4    `json:"user_id"`
	PortionsRemaining pgtype.Numeric `json:"portions_remaining"`
	ExpiresOn         pgtype.Date    `json:"expires_on"`
}

// Add or top-up an item in the pantry. On conflict, adds portions and
// resets expires_on to the new purchase date + shelf life.
func (q *Queries) UpsertPantryItem(ctx context.Context, arg UpsertPantryItemParams) (Pantry, error) {
	row := q.db.QueryRow(ctx, upsertPantryItem,
		arg.ShoppingItemID,
		arg.HouseholdID,
		arg.UserID,
		arg.PortionsRemaining,
		arg.ExpiresOn,
	)
	var i Pantry
	err := row.Scan(
		&i.ID,
		&i.ShoppingItemID,
		&i.HouseholdID,
		&i.UserID,
		&i.PortionsRemaining,
		&i.ExpiresOn,
		&i.Status,
		&i.BoughtAt,
		&i.UpdatedAt,
	)
	return i, err
}
