// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shopping_list.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getShoppingList = `-- name: GetShoppingList :many
SELECT name, item_type, text_id, portions_per_unit, quantity 
FROM shopping_list sl
JOIN shopping_items si ON sl.shopping_item_id = si.id
WHERE household_id = $1 OR user_id = $2
`

type GetShoppingListParams struct {
	HouseholdID pgtype.Int4 `json:"household_id"`
	UserID      pgtype.Int4 `json:"user_id"`
}

type GetShoppingListRow struct {
	Name            string           `json:"name"`
	ItemType        ShoppingItemType `json:"item_type"`
	TextID          pgtype.Text      `json:"text_id"`
	PortionsPerUnit int32            `json:"portions_per_unit"`
	Quantity        int32            `json:"quantity"`
}

func (q *Queries) GetShoppingList(ctx context.Context, arg GetShoppingListParams) ([]GetShoppingListRow, error) {
	rows, err := q.db.Query(ctx, getShoppingList, arg.HouseholdID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShoppingListRow
	for rows.Next() {
		var i GetShoppingListRow
		if err := rows.Scan(
			&i.Name,
			&i.ItemType,
			&i.TextID,
			&i.PortionsPerUnit,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertShoppingList = `-- name: UpsertShoppingList :many
INSERT INTO shopping_list (shopping_item_id, quantity, id, household_id, user_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO UPDATE
SET shopping_item_id = EXCLUDED.shopping_item_id,
    quantity = EXCLUDED.quantity,
    id = EXCLUDED.id,
    household_id = EXCLUDED.household_id,
    user_id = EXCLUDED.user_id
RETURNING id, shopping_item_id, quantity, household_id, user_id
`

type UpsertShoppingListParams struct {
	ShoppingItemID int32       `json:"shopping_item_id"`
	Quantity       int32       `json:"quantity"`
	ID             int32       `json:"id"`
	HouseholdID    pgtype.Int4 `json:"household_id"`
	UserID         pgtype.Int4 `json:"user_id"`
}

func (q *Queries) UpsertShoppingList(ctx context.Context, arg UpsertShoppingListParams) ([]ShoppingList, error) {
	rows, err := q.db.Query(ctx, upsertShoppingList,
		arg.ShoppingItemID,
		arg.Quantity,
		arg.ID,
		arg.HouseholdID,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingList
	for rows.Next() {
		var i ShoppingList
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingItemID,
			&i.Quantity,
			&i.HouseholdID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
