// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shopping_items.sql

package database

import (
	"context"
)

const createShoppingItem = `-- name: CreateShoppingItem :one
INSERT INTO shopping_items (name, item_type, portions_per_unit)
VALUES ($1, $2, $3)
RETURNING id, name, item_type, text_id, portions_per_unit
`

type CreateShoppingItemParams struct {
	Name            string           `json:"name"`
	ItemType        ShoppingItemType `json:"item_type"`
	PortionsPerUnit int32            `json:"portions_per_unit"`
}

func (q *Queries) CreateShoppingItem(ctx context.Context, arg CreateShoppingItemParams) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, createShoppingItem, arg.Name, arg.ItemType, arg.PortionsPerUnit)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ItemType,
		&i.TextID,
		&i.PortionsPerUnit,
	)
	return i, err
}

const getAllShoppingItems = `-- name: GetAllShoppingItems :many
SELECT id, name, item_type, portions_per_unit
FROM shopping_items
`

type GetAllShoppingItemsRow struct {
	ID              int32            `json:"id"`
	Name            string           `json:"name"`
	ItemType        ShoppingItemType `json:"item_type"`
	PortionsPerUnit int32            `json:"portions_per_unit"`
}

func (q *Queries) GetAllShoppingItems(ctx context.Context) ([]GetAllShoppingItemsRow, error) {
	rows, err := q.db.Query(ctx, getAllShoppingItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllShoppingItemsRow
	for rows.Next() {
		var i GetAllShoppingItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ItemType,
			&i.PortionsPerUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShoppingItems = `-- name: ListShoppingItems :many
SELECT id, name, item_type, portions_per_unit
FROM shopping_items
`

type ListShoppingItemsRow struct {
	ID              int32            `json:"id"`
	Name            string           `json:"name"`
	ItemType        ShoppingItemType `json:"item_type"`
	PortionsPerUnit int32            `json:"portions_per_unit"`
}

func (q *Queries) ListShoppingItems(ctx context.Context) ([]ListShoppingItemsRow, error) {
	rows, err := q.db.Query(ctx, listShoppingItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShoppingItemsRow
	for rows.Next() {
		var i ListShoppingItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ItemType,
			&i.PortionsPerUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShoppingItemPortions = `-- name: UpdateShoppingItemPortions :one
UPDATE shopping_items
SET portions_per_unit = $2
WHERE id = $1
RETURNING id, name, item_type, text_id, portions_per_unit
`

type UpdateShoppingItemPortionsParams struct {
	ID              int32 `json:"id"`
	PortionsPerUnit int32 `json:"portions_per_unit"`
}

func (q *Queries) UpdateShoppingItemPortions(ctx context.Context, arg UpdateShoppingItemPortionsParams) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, updateShoppingItemPortions, arg.ID, arg.PortionsPerUnit)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ItemType,
		&i.TextID,
		&i.PortionsPerUnit,
	)
	return i, err
}
