// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shopping_items.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShoppingItem = `-- name: CreateShoppingItem :one
INSERT INTO shopping_items (name, item_type, portions_per_unit, allergens)
VALUES (
    $1, $2, $3,
    COALESCE($4::text[], '{}')
)
RETURNING id, name, item_type, text_id, portions_per_unit, shelf_life_days, allergens
`

type CreateShoppingItemParams struct {
	Name            string           `json:"name"`
	ItemType        ShoppingItemType `json:"item_type"`
	PortionsPerUnit int32            `json:"portions_per_unit"`
	Allergens       []string         `json:"allergens"`
}

func (q *Queries) CreateShoppingItem(ctx context.Context, arg CreateShoppingItemParams) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, createShoppingItem,
		arg.Name,
		arg.ItemType,
		arg.PortionsPerUnit,
		arg.Allergens,
	)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ItemType,
		&i.TextID,
		&i.PortionsPerUnit,
		&i.ShelfLifeDays,
		&i.Allergens,
	)
	return i, err
}

const getAllShoppingItems = `-- name: GetAllShoppingItems :many
SELECT id, name, item_type, portions_per_unit, allergens
FROM shopping_items
`

type GetAllShoppingItemsRow struct {
	ID              int32            `json:"id"`
	Name            string           `json:"name"`
	ItemType        ShoppingItemType `json:"item_type"`
	PortionsPerUnit int32            `json:"portions_per_unit"`
	Allergens       []string         `json:"allergens"`
}

func (q *Queries) GetAllShoppingItems(ctx context.Context) ([]GetAllShoppingItemsRow, error) {
	rows, err := q.db.Query(ctx, getAllShoppingItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllShoppingItemsRow
	for rows.Next() {
		var i GetAllShoppingItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ItemType,
			&i.PortionsPerUnit,
			&i.Allergens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShoppingItems = `-- name: ListShoppingItems :many
SELECT id, name, item_type, portions_per_unit, allergens
FROM shopping_items
`

type ListShoppingItemsRow struct {
	ID              int32            `json:"id"`
	Name            string           `json:"name"`
	ItemType        ShoppingItemType `json:"item_type"`
	PortionsPerUnit int32            `json:"portions_per_unit"`
	Allergens       []string         `json:"allergens"`
}

func (q *Queries) ListShoppingItems(ctx context.Context) ([]ListShoppingItemsRow, error) {
	rows, err := q.db.Query(ctx, listShoppingItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShoppingItemsRow
	for rows.Next() {
		var i ListShoppingItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ItemType,
			&i.PortionsPerUnit,
			&i.Allergens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShoppingItem = `-- name: UpdateShoppingItem :one
UPDATE shopping_items
SET
    name              = COALESCE($1, name),
    item_type         = COALESCE($2, item_type),
    portions_per_unit = COALESCE($3, portions_per_unit),
    allergens         = COALESCE($4::text[], allergens)
WHERE id = $5
RETURNING id, name, item_type, text_id, portions_per_unit, shelf_life_days, allergens
`

type UpdateShoppingItemParams struct {
	Name            pgtype.Text          `json:"name"`
	ItemType        NullShoppingItemType `json:"item_type"`
	PortionsPerUnit pgtype.Int4          `json:"portions_per_unit"`
	Allergens       []string             `json:"allergens"`
	ID              int32                `json:"id"`
}

// Partial update: pass NULL for any field to leave it unchanged. Allergens
// follow the same rule — NULL keeps the existing tags, '{}' clears them.
func (q *Queries) UpdateShoppingItem(ctx context.Context, arg UpdateShoppingItemParams) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, updateShoppingItem,
		arg.Name,
		arg.ItemType,
		arg.PortionsPerUnit,
		arg.Allergens,
		arg.ID,
	)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ItemType,
		&i.TextID,
		&i.PortionsPerUnit,
		&i.ShelfLifeDays,
		&i.Allergens,
	)
	return i, err
}

const updateShoppingItemPortions = `-- name: UpdateShoppingItemPortions :one
UPDATE shopping_items
SET portions_per_unit = $2
WHERE id = $1
RETURNING id, name, item_type, text_id, portions_per_unit, shelf_life_days, allergens
`

type UpdateShoppingItemPortionsParams struct {
	ID              int32 `json:"id"`
	PortionsPerUnit int32 `json:"portions_per_unit"`
}

func (q *Queries) UpdateShoppingItemPortions(ctx context.Context, arg UpdateShoppingItemPortionsParams) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, updateShoppingItemPortions, arg.ID, arg.PortionsPerUnit)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ItemType,
		&i.TextID,
		&i.PortionsPerUnit,
		&i.ShelfLifeDays,
		&i.Allergens,
	)
	return i, err
}
