// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sub_ingredients.sql

package database

import (
	"context"
)

const addSubIngredient = `-- name: AddSubIngredient :one
INSERT INTO sub_ingredients (shopping_item_id, name, allergens, sort_order)
VALUES (
    $1, $2,
    COALESCE($3::text[], '{}'), $4
)
RETURNING id, shopping_item_id, name, allergens, sort_order
`

type AddSubIngredientParams struct {
	ShoppingItemID int32    `json:"shopping_item_id"`
	Name           string   `json:"name"`
	Allergens      []string `json:"allergens"`
	SortOrder      int32    `json:"sort_order"`
}

// Attach a lightweight sub-ingredient (name + allergens) to a shopping item.
func (q *Queries) AddSubIngredient(ctx context.Context, arg AddSubIngredientParams) (SubIngredient, error) {
	row := q.db.QueryRow(ctx, addSubIngredient,
		arg.ShoppingItemID,
		arg.Name,
		arg.Allergens,
		arg.SortOrder,
	)
	var i SubIngredient
	err := row.Scan(
		&i.ID,
		&i.ShoppingItemID,
		&i.Name,
		&i.Allergens,
		&i.SortOrder,
	)
	return i, err
}

const listSubIngredientsForItem = `-- name: ListSubIngredientsForItem :many
SELECT id, shopping_item_id, name, allergens, sort_order
FROM sub_ingredients
WHERE shopping_item_id = $1
ORDER BY sort_order, name
`

// All sub-ingredients belonging to a single shopping item.
func (q *Queries) ListSubIngredientsForItem(ctx context.Context, shoppingItemID int32) ([]SubIngredient, error) {
	rows, err := q.db.Query(ctx, listSubIngredientsForItem, shoppingItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubIngredient
	for rows.Next() {
		var i SubIngredient
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingItemID,
			&i.Name,
			&i.Allergens,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubIngredientsForMeal = `-- name: ListSubIngredientsForMeal :many
SELECT
    sub.id,
    sub.shopping_item_id,
    sub.name,
    sub.allergens,
    sub.sort_order
FROM sub_ingredients sub
JOIN meal_ingredients mi ON mi.shopping_item_id = sub.shopping_item_id
WHERE mi.meal_id = $1
ORDER BY sub.shopping_item_id, sub.sort_order, sub.name
`

// Every sub-ingredient reachable from a meal via its ingredients, so the
// meal view can render each ingredient's breakdown in one round trip.
func (q *Queries) ListSubIngredientsForMeal(ctx context.Context, mealID int32) ([]SubIngredient, error) {
	rows, err := q.db.Query(ctx, listSubIngredientsForMeal, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubIngredient
	for rows.Next() {
		var i SubIngredient
		if err := rows.Scan(
			&i.ID,
			&i.ShoppingItemID,
			&i.Name,
			&i.Allergens,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSubIngredient = `-- name: RemoveSubIngredient :exec
DELETE FROM sub_ingredients
WHERE id = $1
`

func (q *Queries) RemoveSubIngredient(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, removeSubIngredient, id)
	return err
}

const updateSubIngredient = `-- name: UpdateSubIngredient :one
UPDATE sub_ingredients
SET name       = $1,
    allergens  = COALESCE($2::text[], '{}'),
    sort_order = $3
WHERE id = $4
RETURNING id, shopping_item_id, name, allergens, sort_order
`

type UpdateSubIngredientParams struct {
	Name      string   `json:"name"`
	Allergens []string `json:"allergens"`
	SortOrder int32    `json:"sort_order"`
	ID        int32    `json:"id"`
}

func (q *Queries) UpdateSubIngredient(ctx context.Context, arg UpdateSubIngredientParams) (SubIngredient, error) {
	row := q.db.QueryRow(ctx, updateSubIngredient,
		arg.Name,
		arg.Allergens,
		arg.SortOrder,
		arg.ID,
	)
	var i SubIngredient
	err := row.Scan(
		&i.ID,
		&i.ShoppingItemID,
		&i.Name,
		&i.Allergens,
		&i.SortOrder,
	)
	return i, err
}
