// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, name, household, username, password_hash, created_at
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Household,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (name, username, password_hash, household)
VALUES ($1, $2, $3, $4)
`

type InsertUserParams struct {
	Name         string
	Username     string
	PasswordHash string
	Household    pgtype.Int4
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.Name,
		arg.Username,
		arg.PasswordHash,
		arg.Household,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = $1, password_hash = $2
WHERE username = $3
`

type UpdateUserParams struct {
	Name         string
	PasswordHash string
	Username     string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.Name, arg.PasswordHash, arg.Username)
	return err
}
